// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core.proto

/*
Package pipeline is a generated protocol buffer package.

It is generated from these files:
	core.proto

It has these top-level messages:
	SessionContext
	Status
	Response
	SessionRequest
	SessionResponse
	Feature
	PipelineCreateRequest
	Score
	Pipeline
	PipelineCreateResult
	PipelineExecuteRequest
	PipelineExecuteResult
	PipelineListRequest
	PipelineDeleteRequest
	PipelineCancelRequest
	PipelineListResult
	PipelineCreateResultsRequest
	PipelineExecuteResultsRequest
	PipelineExportRequest
	SetProblemDocRequest
*/
package pipeline

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_UNKNOWN             StatusCode = 0
	StatusCode_OK                  StatusCode = 1
	StatusCode_CANCELLED           StatusCode = 2
	StatusCode_SESSION_UNKNOWN     StatusCode = 3
	StatusCode_SESSION_ENDED       StatusCode = 4
	StatusCode_SESSION_EXPIRED     StatusCode = 5
	StatusCode_INVALID_ARGUMENT    StatusCode = 6
	StatusCode_RESOURCE_EXHAUSTED  StatusCode = 7
	StatusCode_UNAVAILABLE         StatusCode = 8
	StatusCode_FAILED_PRECONDITION StatusCode = 9
	StatusCode_OUT_OF_RANGE        StatusCode = 10
	StatusCode_UNIMPLEMENTED       StatusCode = 11
	StatusCode_INTERNAL            StatusCode = 12
	StatusCode_ABORTED             StatusCode = 13
)

var StatusCode_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "OK",
	2:  "CANCELLED",
	3:  "SESSION_UNKNOWN",
	4:  "SESSION_ENDED",
	5:  "SESSION_EXPIRED",
	6:  "INVALID_ARGUMENT",
	7:  "RESOURCE_EXHAUSTED",
	8:  "UNAVAILABLE",
	9:  "FAILED_PRECONDITION",
	10: "OUT_OF_RANGE",
	11: "UNIMPLEMENTED",
	12: "INTERNAL",
	13: "ABORTED",
}
var StatusCode_value = map[string]int32{
	"UNKNOWN":             0,
	"OK":                  1,
	"CANCELLED":           2,
	"SESSION_UNKNOWN":     3,
	"SESSION_ENDED":       4,
	"SESSION_EXPIRED":     5,
	"INVALID_ARGUMENT":    6,
	"RESOURCE_EXHAUSTED":  7,
	"UNAVAILABLE":         8,
	"FAILED_PRECONDITION": 9,
	"OUT_OF_RANGE":        10,
	"UNIMPLEMENTED":       11,
	"INTERNAL":            12,
	"ABORTED":             13,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Progress int32

const (
	Progress_PROGRESS_UNKNOWN Progress = 0
	Progress_SUBMITTED        Progress = 1
	Progress_RUNNING          Progress = 2
	Progress_UPDATED          Progress = 3
	Progress_COMPLETED        Progress = 4
	Progress_ERRORED          Progress = 5
)

var Progress_name = map[int32]string{
	0: "PROGRESS_UNKNOWN",
	1: "SUBMITTED",
	2: "RUNNING",
	3: "UPDATED",
	4: "COMPLETED",
	5: "ERRORED",
}
var Progress_value = map[string]int32{
	"PROGRESS_UNKNOWN": 0,
	"SUBMITTED":        1,
	"RUNNING":          2,
	"UPDATED":          3,
	"COMPLETED":        4,
	"ERRORED":          5,
}

func (x Progress) String() string {
	return proto.EnumName(Progress_name, int32(x))
}
func (Progress) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TaskType int32

const (
	TaskType_TASK_TYPE_UNDEFINED     TaskType = 0
	TaskType_CLASSIFICATION          TaskType = 1
	TaskType_REGRESSION              TaskType = 2
	TaskType_CLUSTERING              TaskType = 3
	TaskType_LINK_PREDICTION         TaskType = 4
	TaskType_VERTEX_NOMINATION       TaskType = 5
	TaskType_COMMUNITY_DETECTION     TaskType = 6
	TaskType_GRAPH_CLUSTERING        TaskType = 7
	TaskType_GRAPH_MATCHING          TaskType = 8
	TaskType_TIME_SERIES_FORECASTING TaskType = 9
	TaskType_COLLABORATIVE_FILTERING TaskType = 10
)

var TaskType_name = map[int32]string{
	0:  "TASK_TYPE_UNDEFINED",
	1:  "CLASSIFICATION",
	2:  "REGRESSION",
	3:  "CLUSTERING",
	4:  "LINK_PREDICTION",
	5:  "VERTEX_NOMINATION",
	6:  "COMMUNITY_DETECTION",
	7:  "GRAPH_CLUSTERING",
	8:  "GRAPH_MATCHING",
	9:  "TIME_SERIES_FORECASTING",
	10: "COLLABORATIVE_FILTERING",
}
var TaskType_value = map[string]int32{
	"TASK_TYPE_UNDEFINED":     0,
	"CLASSIFICATION":          1,
	"REGRESSION":              2,
	"CLUSTERING":              3,
	"LINK_PREDICTION":         4,
	"VERTEX_NOMINATION":       5,
	"COMMUNITY_DETECTION":     6,
	"GRAPH_CLUSTERING":        7,
	"GRAPH_MATCHING":          8,
	"TIME_SERIES_FORECASTING": 9,
	"COLLABORATIVE_FILTERING": 10,
}

func (x TaskType) String() string {
	return proto.EnumName(TaskType_name, int32(x))
}
func (TaskType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TaskSubtype int32

const (
	TaskSubtype_TASK_SUBTYPE_UNDEFINED TaskSubtype = 0
	TaskSubtype_NONE                   TaskSubtype = 1
	TaskSubtype_BINARY                 TaskSubtype = 2
	TaskSubtype_MULTICLASS             TaskSubtype = 3
	TaskSubtype_MULTILABEL             TaskSubtype = 4
	TaskSubtype_UNIVARIATE             TaskSubtype = 5
	TaskSubtype_MULTIVARIATE           TaskSubtype = 6
	TaskSubtype_OVERLAPPING            TaskSubtype = 7
	TaskSubtype_NONOVERLAPPING         TaskSubtype = 8
)

var TaskSubtype_name = map[int32]string{
	0: "TASK_SUBTYPE_UNDEFINED",
	1: "NONE",
	2: "BINARY",
	3: "MULTICLASS",
	4: "MULTILABEL",
	5: "UNIVARIATE",
	6: "MULTIVARIATE",
	7: "OVERLAPPING",
	8: "NONOVERLAPPING",
}
var TaskSubtype_value = map[string]int32{
	"TASK_SUBTYPE_UNDEFINED": 0,
	"NONE":           1,
	"BINARY":         2,
	"MULTICLASS":     3,
	"MULTILABEL":     4,
	"UNIVARIATE":     5,
	"MULTIVARIATE":   6,
	"OVERLAPPING":    7,
	"NONOVERLAPPING": 8,
}

func (x TaskSubtype) String() string {
	return proto.EnumName(TaskSubtype_name, int32(x))
}
func (TaskSubtype) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type OutputType int32

const (
	OutputType_OUTPUT_TYPE_UNDEFINED OutputType = 0
)

var OutputType_name = map[int32]string{
	0: "OUTPUT_TYPE_UNDEFINED",
}
var OutputType_value = map[string]int32{
	"OUTPUT_TYPE_UNDEFINED": 0,
}

func (x OutputType) String() string {
	return proto.EnumName(OutputType_name, int32(x))
}
func (OutputType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PerformanceMetric int32

const (
	PerformanceMetric_METRIC_UNDEFINED              PerformanceMetric = 0
	PerformanceMetric_EXECUTION_TIME                PerformanceMetric = 1
	PerformanceMetric_ACCURACY                      PerformanceMetric = 2
	PerformanceMetric_F1                            PerformanceMetric = 3
	PerformanceMetric_F1_MICRO                      PerformanceMetric = 4
	PerformanceMetric_F1_MACRO                      PerformanceMetric = 5
	PerformanceMetric_ROC_AUC                       PerformanceMetric = 6
	PerformanceMetric_ROC_AUC_MICRO                 PerformanceMetric = 7
	PerformanceMetric_ROC_AUC_MACRO                 PerformanceMetric = 8
	PerformanceMetric_MEAN_SQUARED_ERROR            PerformanceMetric = 9
	PerformanceMetric_ROOT_MEAN_SQUARED_ERROR       PerformanceMetric = 10
	PerformanceMetric_ROOT_MEAN_SQUARED_ERROR_AVG   PerformanceMetric = 11
	PerformanceMetric_MEAN_ABSOLUTE_ERROR           PerformanceMetric = 12
	PerformanceMetric_R_SQUARED                     PerformanceMetric = 13
	PerformanceMetric_NORMALIZED_MUTUAL_INFORMATION PerformanceMetric = 14
	PerformanceMetric_JACCARD_SIMILARITY_SCORE      PerformanceMetric = 15
)

var PerformanceMetric_name = map[int32]string{
	0:  "METRIC_UNDEFINED",
	1:  "EXECUTION_TIME",
	2:  "ACCURACY",
	3:  "F1",
	4:  "F1_MICRO",
	5:  "F1_MACRO",
	6:  "ROC_AUC",
	7:  "ROC_AUC_MICRO",
	8:  "ROC_AUC_MACRO",
	9:  "MEAN_SQUARED_ERROR",
	10: "ROOT_MEAN_SQUARED_ERROR",
	11: "ROOT_MEAN_SQUARED_ERROR_AVG",
	12: "MEAN_ABSOLUTE_ERROR",
	13: "R_SQUARED",
	14: "NORMALIZED_MUTUAL_INFORMATION",
	15: "JACCARD_SIMILARITY_SCORE",
}
var PerformanceMetric_value = map[string]int32{
	"METRIC_UNDEFINED":              0,
	"EXECUTION_TIME":                1,
	"ACCURACY":                      2,
	"F1":                            3,
	"F1_MICRO":                      4,
	"F1_MACRO":                      5,
	"ROC_AUC":                       6,
	"ROC_AUC_MICRO":                 7,
	"ROC_AUC_MACRO":                 8,
	"MEAN_SQUARED_ERROR":            9,
	"ROOT_MEAN_SQUARED_ERROR":       10,
	"ROOT_MEAN_SQUARED_ERROR_AVG":   11,
	"MEAN_ABSOLUTE_ERROR":           12,
	"R_SQUARED":                     13,
	"NORMALIZED_MUTUAL_INFORMATION": 14,
	"JACCARD_SIMILARITY_SCORE":      15,
}

func (x PerformanceMetric) String() string {
	return proto.EnumName(PerformanceMetric_name, int32(x))
}
func (PerformanceMetric) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SessionContext struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *SessionContext) Reset()                    { *m = SessionContext{} }
func (m *SessionContext) String() string            { return proto.CompactTextString(m) }
func (*SessionContext) ProtoMessage()               {}
func (*SessionContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SessionContext) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type Status struct {
	Code    StatusCode `protobuf:"varint,1,opt,name=code,enum=StatusCode" json:"code,omitempty"`
	Details string     `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Status) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_UNKNOWN
}

func (m *Status) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type Response struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// in the future we could also pass arguments allowing one to fork an existing session,
// or provide resource limits on a session (asking TA2 system to terminate work if it exceeds a given limit)
type SessionRequest struct {
	UserAgent string `protobuf:"bytes,1,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *SessionRequest) Reset()                    { *m = SessionRequest{} }
func (m *SessionRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()               {}
func (*SessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SessionRequest) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *SessionRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SessionResponse struct {
	ResponseInfo *Response       `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	UserAgent    string          `protobuf:"bytes,2,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Version      string          `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Context      *SessionContext `protobuf:"bytes,4,opt,name=context" json:"context,omitempty"`
}

func (m *SessionResponse) Reset()                    { *m = SessionResponse{} }
func (m *SessionResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()               {}
func (*SessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SessionResponse) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *SessionResponse) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *SessionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SessionResponse) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type Feature struct {
	ResourceId string `protobuf:"bytes,1,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	// be set to a string value of '0' when working with a raw CSV file rather than a D3M dataset.
	FeatureName string `protobuf:"bytes,2,opt,name=feature_name,json=featureName" json:"feature_name,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Feature) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *Feature) GetFeatureName() string {
	if m != nil {
		return m.FeatureName
	}
	return ""
}

type PipelineCreateRequest struct {
	Context         *SessionContext     `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	DatasetUri      string              `protobuf:"bytes,2,opt,name=dataset_uri,json=datasetUri" json:"dataset_uri,omitempty"`
	Task            TaskType            `protobuf:"varint,3,opt,name=task,enum=TaskType" json:"task,omitempty"`
	TaskSubtype     TaskSubtype         `protobuf:"varint,4,opt,name=task_subtype,json=taskSubtype,enum=TaskSubtype" json:"task_subtype,omitempty"`
	TaskDescription string              `protobuf:"bytes,5,opt,name=task_description,json=taskDescription" json:"task_description,omitempty"`
	Output          OutputType          `protobuf:"varint,6,opt,name=output,enum=OutputType" json:"output,omitempty"`
	Metrics         []PerformanceMetric `protobuf:"varint,7,rep,packed,name=metrics,enum=PerformanceMetric" json:"metrics,omitempty"`
	TargetFeatures  []*Feature          `protobuf:"bytes,8,rep,name=target_features,json=targetFeatures" json:"target_features,omitempty"`
	PredictFeatures []*Feature          `protobuf:"bytes,9,rep,name=predict_features,json=predictFeatures" json:"predict_features,omitempty"`
	MaxPipelines    int32               `protobuf:"varint,10,opt,name=max_pipelines,json=maxPipelines" json:"max_pipelines,omitempty"`
}

func (m *PipelineCreateRequest) Reset()                    { *m = PipelineCreateRequest{} }
func (m *PipelineCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineCreateRequest) ProtoMessage()               {}
func (*PipelineCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PipelineCreateRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineCreateRequest) GetDatasetUri() string {
	if m != nil {
		return m.DatasetUri
	}
	return ""
}

func (m *PipelineCreateRequest) GetTask() TaskType {
	if m != nil {
		return m.Task
	}
	return TaskType_TASK_TYPE_UNDEFINED
}

func (m *PipelineCreateRequest) GetTaskSubtype() TaskSubtype {
	if m != nil {
		return m.TaskSubtype
	}
	return TaskSubtype_TASK_SUBTYPE_UNDEFINED
}

func (m *PipelineCreateRequest) GetTaskDescription() string {
	if m != nil {
		return m.TaskDescription
	}
	return ""
}

func (m *PipelineCreateRequest) GetOutput() OutputType {
	if m != nil {
		return m.Output
	}
	return OutputType_OUTPUT_TYPE_UNDEFINED
}

func (m *PipelineCreateRequest) GetMetrics() []PerformanceMetric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *PipelineCreateRequest) GetTargetFeatures() []*Feature {
	if m != nil {
		return m.TargetFeatures
	}
	return nil
}

func (m *PipelineCreateRequest) GetPredictFeatures() []*Feature {
	if m != nil {
		return m.PredictFeatures
	}
	return nil
}

func (m *PipelineCreateRequest) GetMaxPipelines() int32 {
	if m != nil {
		return m.MaxPipelines
	}
	return 0
}

type Score struct {
	Metric PerformanceMetric `protobuf:"varint,1,opt,name=metric,enum=PerformanceMetric" json:"metric,omitempty"`
	Value  float32           `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
}

func (m *Score) Reset()                    { *m = Score{} }
func (m *Score) String() string            { return proto.CompactTextString(m) }
func (*Score) ProtoMessage()               {}
func (*Score) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Score) GetMetric() PerformanceMetric {
	if m != nil {
		return m.Metric
	}
	return PerformanceMetric_METRIC_UNDEFINED
}

func (m *Score) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Pipeline struct {
	PredictResultUri string     `protobuf:"bytes,1,opt,name=predict_result_uri,json=predictResultUri" json:"predict_result_uri,omitempty"`
	Output           OutputType `protobuf:"varint,2,opt,name=output,enum=OutputType" json:"output,omitempty"`
	Scores           []*Score   `protobuf:"bytes,3,rep,name=scores" json:"scores,omitempty"`
}

func (m *Pipeline) Reset()                    { *m = Pipeline{} }
func (m *Pipeline) String() string            { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()               {}
func (*Pipeline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Pipeline) GetPredictResultUri() string {
	if m != nil {
		return m.PredictResultUri
	}
	return ""
}

func (m *Pipeline) GetOutput() OutputType {
	if m != nil {
		return m.Output
	}
	return OutputType_OUTPUT_TYPE_UNDEFINED
}

func (m *Pipeline) GetScores() []*Score {
	if m != nil {
		return m.Scores
	}
	return nil
}

type PipelineCreateResult struct {
	ResponseInfo *Response `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	// and the stream should be closed immediately
	// if pipeline_id is set and this is an error, it concerns only that single pipeline
	// (progress_info should be set to ERRORED) and the create process will continue to
	// create and train the other pipelines
	ProgressInfo Progress `protobuf:"varint,2,opt,name=progress_info,json=progressInfo,enum=Progress" json:"progress_info,omitempty"`
	// pipeline failed and unavailable for ExecutePipeline or ExportPipeline
	PipelineId string `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	// Will be set if progress info value is UPDATED or COMPLETED
	PipelineInfo *Pipeline `protobuf:"bytes,4,opt,name=pipeline_info,json=pipelineInfo" json:"pipeline_info,omitempty"`
}

func (m *PipelineCreateResult) Reset()                    { *m = PipelineCreateResult{} }
func (m *PipelineCreateResult) String() string            { return proto.CompactTextString(m) }
func (*PipelineCreateResult) ProtoMessage()               {}
func (*PipelineCreateResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PipelineCreateResult) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *PipelineCreateResult) GetProgressInfo() Progress {
	if m != nil {
		return m.ProgressInfo
	}
	return Progress_PROGRESS_UNKNOWN
}

func (m *PipelineCreateResult) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineCreateResult) GetPipelineInfo() *Pipeline {
	if m != nil {
		return m.PipelineInfo
	}
	return nil
}

type PipelineExecuteRequest struct {
	Context    *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	PipelineId string          `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	DatasetUri string          `protobuf:"bytes,3,opt,name=dataset_uri,json=datasetUri" json:"dataset_uri,omitempty"`
}

func (m *PipelineExecuteRequest) Reset()                    { *m = PipelineExecuteRequest{} }
func (m *PipelineExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineExecuteRequest) ProtoMessage()               {}
func (*PipelineExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PipelineExecuteRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineExecuteRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineExecuteRequest) GetDatasetUri() string {
	if m != nil {
		return m.DatasetUri
	}
	return ""
}

type PipelineExecuteResult struct {
	ResponseInfo *Response `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	ProgressInfo Progress  `protobuf:"varint,2,opt,name=progress_info,json=progressInfo,enum=Progress" json:"progress_info,omitempty"`
	PipelineId   string    `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	// Will be set if progress info value is UPDATED or COMPLETED
	ResultUri string `protobuf:"bytes,4,opt,name=result_uri,json=resultUri" json:"result_uri,omitempty"`
}

func (m *PipelineExecuteResult) Reset()                    { *m = PipelineExecuteResult{} }
func (m *PipelineExecuteResult) String() string            { return proto.CompactTextString(m) }
func (*PipelineExecuteResult) ProtoMessage()               {}
func (*PipelineExecuteResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PipelineExecuteResult) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *PipelineExecuteResult) GetProgressInfo() Progress {
	if m != nil {
		return m.ProgressInfo
	}
	return Progress_PROGRESS_UNKNOWN
}

func (m *PipelineExecuteResult) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineExecuteResult) GetResultUri() string {
	if m != nil {
		return m.ResultUri
	}
	return ""
}

type PipelineListRequest struct {
	Context *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
}

func (m *PipelineListRequest) Reset()                    { *m = PipelineListRequest{} }
func (m *PipelineListRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineListRequest) ProtoMessage()               {}
func (*PipelineListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PipelineListRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type PipelineDeleteRequest struct {
	Context           *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	DeletePipelineIds []string        `protobuf:"bytes,2,rep,name=delete_pipeline_ids,json=deletePipelineIds" json:"delete_pipeline_ids,omitempty"`
}

func (m *PipelineDeleteRequest) Reset()                    { *m = PipelineDeleteRequest{} }
func (m *PipelineDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineDeleteRequest) ProtoMessage()               {}
func (*PipelineDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PipelineDeleteRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineDeleteRequest) GetDeletePipelineIds() []string {
	if m != nil {
		return m.DeletePipelineIds
	}
	return nil
}

type PipelineCancelRequest struct {
	Context           *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	CancelPipelineIds []string        `protobuf:"bytes,2,rep,name=cancel_pipeline_ids,json=cancelPipelineIds" json:"cancel_pipeline_ids,omitempty"`
}

func (m *PipelineCancelRequest) Reset()                    { *m = PipelineCancelRequest{} }
func (m *PipelineCancelRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineCancelRequest) ProtoMessage()               {}
func (*PipelineCancelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PipelineCancelRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineCancelRequest) GetCancelPipelineIds() []string {
	if m != nil {
		return m.CancelPipelineIds
	}
	return nil
}

type PipelineListResult struct {
	ResponseInfo *Response `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	PipelineIds  []string  `protobuf:"bytes,2,rep,name=pipeline_ids,json=pipelineIds" json:"pipeline_ids,omitempty"`
}

func (m *PipelineListResult) Reset()                    { *m = PipelineListResult{} }
func (m *PipelineListResult) String() string            { return proto.CompactTextString(m) }
func (*PipelineListResult) ProtoMessage()               {}
func (*PipelineListResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PipelineListResult) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *PipelineListResult) GetPipelineIds() []string {
	if m != nil {
		return m.PipelineIds
	}
	return nil
}

type PipelineCreateResultsRequest struct {
	Context     *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	PipelineIds []string        `protobuf:"bytes,2,rep,name=pipeline_ids,json=pipelineIds" json:"pipeline_ids,omitempty"`
}

func (m *PipelineCreateResultsRequest) Reset()                    { *m = PipelineCreateResultsRequest{} }
func (m *PipelineCreateResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineCreateResultsRequest) ProtoMessage()               {}
func (*PipelineCreateResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PipelineCreateResultsRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineCreateResultsRequest) GetPipelineIds() []string {
	if m != nil {
		return m.PipelineIds
	}
	return nil
}

type PipelineExecuteResultsRequest struct {
	Context     *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	PipelineIds []string        `protobuf:"bytes,2,rep,name=pipeline_ids,json=pipelineIds" json:"pipeline_ids,omitempty"`
}

func (m *PipelineExecuteResultsRequest) Reset()                    { *m = PipelineExecuteResultsRequest{} }
func (m *PipelineExecuteResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineExecuteResultsRequest) ProtoMessage()               {}
func (*PipelineExecuteResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PipelineExecuteResultsRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineExecuteResultsRequest) GetPipelineIds() []string {
	if m != nil {
		return m.PipelineIds
	}
	return nil
}

type PipelineExportRequest struct {
	Context         *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	PipelineId      string          `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	PipelineExecUri string          `protobuf:"bytes,3,opt,name=pipeline_exec_uri,json=pipelineExecUri" json:"pipeline_exec_uri,omitempty"`
}

func (m *PipelineExportRequest) Reset()                    { *m = PipelineExportRequest{} }
func (m *PipelineExportRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineExportRequest) ProtoMessage()               {}
func (*PipelineExportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *PipelineExportRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineExportRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineExportRequest) GetPipelineExecUri() string {
	if m != nil {
		return m.PipelineExecUri
	}
	return ""
}

type SetProblemDocRequest struct {
	Updates []*SetProblemDocRequest_ReplaceProblemDocField `protobuf:"bytes,1,rep,name=updates" json:"updates,omitempty"`
	Context *SessionContext                                `protobuf:"bytes,2,opt,name=context" json:"context,omitempty"`
}

func (m *SetProblemDocRequest) Reset()                    { *m = SetProblemDocRequest{} }
func (m *SetProblemDocRequest) String() string            { return proto.CompactTextString(m) }
func (*SetProblemDocRequest) ProtoMessage()               {}
func (*SetProblemDocRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *SetProblemDocRequest) GetUpdates() []*SetProblemDocRequest_ReplaceProblemDocField {
	if m != nil {
		return m.Updates
	}
	return nil
}

func (m *SetProblemDocRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type SetProblemDocRequest_ReplaceProblemDocField struct {
	// Types that are valid to be assigned to Update:
	//	*SetProblemDocRequest_ReplaceProblemDocField_TaskType
	//	*SetProblemDocRequest_ReplaceProblemDocField_TaskSubtype
	//	*SetProblemDocRequest_ReplaceProblemDocField_TaskDescription
	//	*SetProblemDocRequest_ReplaceProblemDocField_OutputType
	//	*SetProblemDocRequest_ReplaceProblemDocField_Metric
	Update isSetProblemDocRequest_ReplaceProblemDocField_Update `protobuf_oneof:"update"`
}

func (m *SetProblemDocRequest_ReplaceProblemDocField) Reset() {
	*m = SetProblemDocRequest_ReplaceProblemDocField{}
}
func (m *SetProblemDocRequest_ReplaceProblemDocField) String() string {
	return proto.CompactTextString(m)
}
func (*SetProblemDocRequest_ReplaceProblemDocField) ProtoMessage() {}
func (*SetProblemDocRequest_ReplaceProblemDocField) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{19, 0}
}

type isSetProblemDocRequest_ReplaceProblemDocField_Update interface {
	isSetProblemDocRequest_ReplaceProblemDocField_Update()
}

type SetProblemDocRequest_ReplaceProblemDocField_TaskType struct {
	TaskType TaskType `protobuf:"varint,1,opt,name=task_type,json=taskType,enum=TaskType,oneof"`
}
type SetProblemDocRequest_ReplaceProblemDocField_TaskSubtype struct {
	TaskSubtype TaskSubtype `protobuf:"varint,2,opt,name=task_subtype,json=taskSubtype,enum=TaskSubtype,oneof"`
}
type SetProblemDocRequest_ReplaceProblemDocField_TaskDescription struct {
	TaskDescription string `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,oneof"`
}
type SetProblemDocRequest_ReplaceProblemDocField_OutputType struct {
	OutputType OutputType `protobuf:"varint,4,opt,name=output_type,json=outputType,enum=OutputType,oneof"`
}
type SetProblemDocRequest_ReplaceProblemDocField_Metric struct {
	Metric PerformanceMetric `protobuf:"varint,5,opt,name=metric,enum=PerformanceMetric,oneof"`
}

func (*SetProblemDocRequest_ReplaceProblemDocField_TaskType) isSetProblemDocRequest_ReplaceProblemDocField_Update() {
}
func (*SetProblemDocRequest_ReplaceProblemDocField_TaskSubtype) isSetProblemDocRequest_ReplaceProblemDocField_Update() {
}
func (*SetProblemDocRequest_ReplaceProblemDocField_TaskDescription) isSetProblemDocRequest_ReplaceProblemDocField_Update() {
}
func (*SetProblemDocRequest_ReplaceProblemDocField_OutputType) isSetProblemDocRequest_ReplaceProblemDocField_Update() {
}
func (*SetProblemDocRequest_ReplaceProblemDocField_Metric) isSetProblemDocRequest_ReplaceProblemDocField_Update() {
}

func (m *SetProblemDocRequest_ReplaceProblemDocField) GetUpdate() isSetProblemDocRequest_ReplaceProblemDocField_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *SetProblemDocRequest_ReplaceProblemDocField) GetTaskType() TaskType {
	if x, ok := m.GetUpdate().(*SetProblemDocRequest_ReplaceProblemDocField_TaskType); ok {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNDEFINED
}

func (m *SetProblemDocRequest_ReplaceProblemDocField) GetTaskSubtype() TaskSubtype {
	if x, ok := m.GetUpdate().(*SetProblemDocRequest_ReplaceProblemDocField_TaskSubtype); ok {
		return x.TaskSubtype
	}
	return TaskSubtype_TASK_SUBTYPE_UNDEFINED
}

func (m *SetProblemDocRequest_ReplaceProblemDocField) GetTaskDescription() string {
	if x, ok := m.GetUpdate().(*SetProblemDocRequest_ReplaceProblemDocField_TaskDescription); ok {
		return x.TaskDescription
	}
	return ""
}

func (m *SetProblemDocRequest_ReplaceProblemDocField) GetOutputType() OutputType {
	if x, ok := m.GetUpdate().(*SetProblemDocRequest_ReplaceProblemDocField_OutputType); ok {
		return x.OutputType
	}
	return OutputType_OUTPUT_TYPE_UNDEFINED
}

func (m *SetProblemDocRequest_ReplaceProblemDocField) GetMetric() PerformanceMetric {
	if x, ok := m.GetUpdate().(*SetProblemDocRequest_ReplaceProblemDocField_Metric); ok {
		return x.Metric
	}
	return PerformanceMetric_METRIC_UNDEFINED
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SetProblemDocRequest_ReplaceProblemDocField) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SetProblemDocRequest_ReplaceProblemDocField_OneofMarshaler, _SetProblemDocRequest_ReplaceProblemDocField_OneofUnmarshaler, _SetProblemDocRequest_ReplaceProblemDocField_OneofSizer, []interface{}{
		(*SetProblemDocRequest_ReplaceProblemDocField_TaskType)(nil),
		(*SetProblemDocRequest_ReplaceProblemDocField_TaskSubtype)(nil),
		(*SetProblemDocRequest_ReplaceProblemDocField_TaskDescription)(nil),
		(*SetProblemDocRequest_ReplaceProblemDocField_OutputType)(nil),
		(*SetProblemDocRequest_ReplaceProblemDocField_Metric)(nil),
	}
}

func _SetProblemDocRequest_ReplaceProblemDocField_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SetProblemDocRequest_ReplaceProblemDocField)
	// update
	switch x := m.Update.(type) {
	case *SetProblemDocRequest_ReplaceProblemDocField_TaskType:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.TaskType))
	case *SetProblemDocRequest_ReplaceProblemDocField_TaskSubtype:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.TaskSubtype))
	case *SetProblemDocRequest_ReplaceProblemDocField_TaskDescription:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.TaskDescription)
	case *SetProblemDocRequest_ReplaceProblemDocField_OutputType:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.OutputType))
	case *SetProblemDocRequest_ReplaceProblemDocField_Metric:
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Metric))
	case nil:
	default:
		return fmt.Errorf("SetProblemDocRequest_ReplaceProblemDocField.Update has unexpected type %T", x)
	}
	return nil
}

func _SetProblemDocRequest_ReplaceProblemDocField_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SetProblemDocRequest_ReplaceProblemDocField)
	switch tag {
	case 1: // update.task_type
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Update = &SetProblemDocRequest_ReplaceProblemDocField_TaskType{TaskType(x)}
		return true, err
	case 2: // update.task_subtype
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Update = &SetProblemDocRequest_ReplaceProblemDocField_TaskSubtype{TaskSubtype(x)}
		return true, err
	case 3: // update.task_description
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Update = &SetProblemDocRequest_ReplaceProblemDocField_TaskDescription{x}
		return true, err
	case 4: // update.output_type
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Update = &SetProblemDocRequest_ReplaceProblemDocField_OutputType{OutputType(x)}
		return true, err
	case 5: // update.metric
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Update = &SetProblemDocRequest_ReplaceProblemDocField_Metric{PerformanceMetric(x)}
		return true, err
	default:
		return false, nil
	}
}

func _SetProblemDocRequest_ReplaceProblemDocField_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SetProblemDocRequest_ReplaceProblemDocField)
	// update
	switch x := m.Update.(type) {
	case *SetProblemDocRequest_ReplaceProblemDocField_TaskType:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.TaskType))
	case *SetProblemDocRequest_ReplaceProblemDocField_TaskSubtype:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.TaskSubtype))
	case *SetProblemDocRequest_ReplaceProblemDocField_TaskDescription:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.TaskDescription)))
		n += len(x.TaskDescription)
	case *SetProblemDocRequest_ReplaceProblemDocField_OutputType:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.OutputType))
	case *SetProblemDocRequest_ReplaceProblemDocField_Metric:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Metric))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

var E_ProtocolVersion = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         54100,
	Name:          "protocol_version",
	Tag:           "bytes,54100,opt,name=protocol_version,json=protocolVersion",
	Filename:      "core.proto",
}

func init() {
	proto.RegisterType((*SessionContext)(nil), "SessionContext")
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*SessionRequest)(nil), "SessionRequest")
	proto.RegisterType((*SessionResponse)(nil), "SessionResponse")
	proto.RegisterType((*Feature)(nil), "Feature")
	proto.RegisterType((*PipelineCreateRequest)(nil), "PipelineCreateRequest")
	proto.RegisterType((*Score)(nil), "Score")
	proto.RegisterType((*Pipeline)(nil), "Pipeline")
	proto.RegisterType((*PipelineCreateResult)(nil), "PipelineCreateResult")
	proto.RegisterType((*PipelineExecuteRequest)(nil), "PipelineExecuteRequest")
	proto.RegisterType((*PipelineExecuteResult)(nil), "PipelineExecuteResult")
	proto.RegisterType((*PipelineListRequest)(nil), "PipelineListRequest")
	proto.RegisterType((*PipelineDeleteRequest)(nil), "PipelineDeleteRequest")
	proto.RegisterType((*PipelineCancelRequest)(nil), "PipelineCancelRequest")
	proto.RegisterType((*PipelineListResult)(nil), "PipelineListResult")
	proto.RegisterType((*PipelineCreateResultsRequest)(nil), "PipelineCreateResultsRequest")
	proto.RegisterType((*PipelineExecuteResultsRequest)(nil), "PipelineExecuteResultsRequest")
	proto.RegisterType((*PipelineExportRequest)(nil), "PipelineExportRequest")
	proto.RegisterType((*SetProblemDocRequest)(nil), "SetProblemDocRequest")
	proto.RegisterType((*SetProblemDocRequest_ReplaceProblemDocField)(nil), "SetProblemDocRequest.ReplaceProblemDocField")
	proto.RegisterEnum("StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("Progress", Progress_name, Progress_value)
	proto.RegisterEnum("TaskType", TaskType_name, TaskType_value)
	proto.RegisterEnum("TaskSubtype", TaskSubtype_name, TaskSubtype_value)
	proto.RegisterEnum("OutputType", OutputType_name, OutputType_value)
	proto.RegisterEnum("PerformanceMetric", PerformanceMetric_name, PerformanceMetric_value)
	proto.RegisterExtension(E_ProtocolVersion)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Core service

type CoreClient interface {
	// Train step - multiple result messages returned via GRPC streaming.
	// Request the TA2 system generate pipelines to satisfy a given task,
	// training data, and targets.  The response is a stream of result messages
	// indicating progress, failure, or completion of an individual pipeline
	// creation task associated with the request.  The stream is closed by the
	// server when all pipeline creation tasks have been completed.
	CreatePipelines(ctx context.Context, in *PipelineCreateRequest, opts ...grpc.CallOption) (Core_CreatePipelinesClient, error)
	// Predict step - multiple results messages returned via GRPC streaming.
	// Request the TA2 system execute a previously created pipeline against an
	// input dataset.  This response is a stream of result messages indicating
	// progress, failure, or completion of the pipeline execution task.  The
	// stream is closed by the server when all pipeline execution tasks have
	// been completed. Labels / predicted values are made available to TA3
	// systems for user inspection.
	ExecutePipeline(ctx context.Context, in *PipelineExecuteRequest, opts ...grpc.CallOption) (Core_ExecutePipelineClient, error)
	// Lists all pipelines in session.
	ListPipelines(ctx context.Context, in *PipelineListRequest, opts ...grpc.CallOption) (*PipelineListResult, error)
	// Deletes specified pipelines in session, returns IDs of successfully deleted pipelines.
	DeletePipelines(ctx context.Context, in *PipelineDeleteRequest, opts ...grpc.CallOption) (*PipelineListResult, error)
	// Cancels processing (creation or execution) of specified pipelines in session, but does not
	// delete.  Returns IDs of successfully canceled pipelines.  State of a canceled pipeline is
	// unspecified.  It could be useable or not.
	CancelPipelines(ctx context.Context, in *PipelineCancelRequest, opts ...grpc.CallOption) (*PipelineListResult, error)
	// Obtain results; lists existing pipelines then streams new results as they become available.
	GetCreatePipelineResults(ctx context.Context, in *PipelineCreateResultsRequest, opts ...grpc.CallOption) (Core_GetCreatePipelineResultsClient, error)
	GetExecutePipelineResults(ctx context.Context, in *PipelineExecuteResultsRequest, opts ...grpc.CallOption) (Core_GetExecutePipelineResultsClient, error)
	// Export executable of a pipeline, including any optional preprocessing used in session.
	ExportPipeline(ctx context.Context, in *PipelineExportRequest, opts ...grpc.CallOption) (*Response, error)
	// Set problem schema for current session.
	SetProblemDoc(ctx context.Context, in *SetProblemDocRequest, opts ...grpc.CallOption) (*Response, error)
	// Session management.
	// Create a new user session, which provides a session context for creation and execution of pipelines.
	StartSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	// Terminate a user session and release associated context resources.
	EndSession(ctx context.Context, in *SessionContext, opts ...grpc.CallOption) (*Response, error)
}

type coreClient struct {
	cc *grpc.ClientConn
}

func NewCoreClient(cc *grpc.ClientConn) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) CreatePipelines(ctx context.Context, in *PipelineCreateRequest, opts ...grpc.CallOption) (Core_CreatePipelinesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Core_serviceDesc.Streams[0], c.cc, "/Core/CreatePipelines", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreCreatePipelinesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_CreatePipelinesClient interface {
	Recv() (*PipelineCreateResult, error)
	grpc.ClientStream
}

type coreCreatePipelinesClient struct {
	grpc.ClientStream
}

func (x *coreCreatePipelinesClient) Recv() (*PipelineCreateResult, error) {
	m := new(PipelineCreateResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreClient) ExecutePipeline(ctx context.Context, in *PipelineExecuteRequest, opts ...grpc.CallOption) (Core_ExecutePipelineClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Core_serviceDesc.Streams[1], c.cc, "/Core/ExecutePipeline", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreExecutePipelineClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_ExecutePipelineClient interface {
	Recv() (*PipelineExecuteResult, error)
	grpc.ClientStream
}

type coreExecutePipelineClient struct {
	grpc.ClientStream
}

func (x *coreExecutePipelineClient) Recv() (*PipelineExecuteResult, error) {
	m := new(PipelineExecuteResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreClient) ListPipelines(ctx context.Context, in *PipelineListRequest, opts ...grpc.CallOption) (*PipelineListResult, error) {
	out := new(PipelineListResult)
	err := grpc.Invoke(ctx, "/Core/ListPipelines", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) DeletePipelines(ctx context.Context, in *PipelineDeleteRequest, opts ...grpc.CallOption) (*PipelineListResult, error) {
	out := new(PipelineListResult)
	err := grpc.Invoke(ctx, "/Core/DeletePipelines", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) CancelPipelines(ctx context.Context, in *PipelineCancelRequest, opts ...grpc.CallOption) (*PipelineListResult, error) {
	out := new(PipelineListResult)
	err := grpc.Invoke(ctx, "/Core/CancelPipelines", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetCreatePipelineResults(ctx context.Context, in *PipelineCreateResultsRequest, opts ...grpc.CallOption) (Core_GetCreatePipelineResultsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Core_serviceDesc.Streams[2], c.cc, "/Core/GetCreatePipelineResults", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreGetCreatePipelineResultsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_GetCreatePipelineResultsClient interface {
	Recv() (*PipelineCreateResult, error)
	grpc.ClientStream
}

type coreGetCreatePipelineResultsClient struct {
	grpc.ClientStream
}

func (x *coreGetCreatePipelineResultsClient) Recv() (*PipelineCreateResult, error) {
	m := new(PipelineCreateResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreClient) GetExecutePipelineResults(ctx context.Context, in *PipelineExecuteResultsRequest, opts ...grpc.CallOption) (Core_GetExecutePipelineResultsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Core_serviceDesc.Streams[3], c.cc, "/Core/GetExecutePipelineResults", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreGetExecutePipelineResultsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_GetExecutePipelineResultsClient interface {
	Recv() (*PipelineExecuteResult, error)
	grpc.ClientStream
}

type coreGetExecutePipelineResultsClient struct {
	grpc.ClientStream
}

func (x *coreGetExecutePipelineResultsClient) Recv() (*PipelineExecuteResult, error) {
	m := new(PipelineExecuteResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreClient) ExportPipeline(ctx context.Context, in *PipelineExportRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Core/ExportPipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) SetProblemDoc(ctx context.Context, in *SetProblemDocRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Core/SetProblemDoc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) StartSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := grpc.Invoke(ctx, "/Core/StartSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) EndSession(ctx context.Context, in *SessionContext, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Core/EndSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Core service

type CoreServer interface {
	// Train step - multiple result messages returned via GRPC streaming.
	// Request the TA2 system generate pipelines to satisfy a given task,
	// training data, and targets.  The response is a stream of result messages
	// indicating progress, failure, or completion of an individual pipeline
	// creation task associated with the request.  The stream is closed by the
	// server when all pipeline creation tasks have been completed.
	CreatePipelines(*PipelineCreateRequest, Core_CreatePipelinesServer) error
	// Predict step - multiple results messages returned via GRPC streaming.
	// Request the TA2 system execute a previously created pipeline against an
	// input dataset.  This response is a stream of result messages indicating
	// progress, failure, or completion of the pipeline execution task.  The
	// stream is closed by the server when all pipeline execution tasks have
	// been completed. Labels / predicted values are made available to TA3
	// systems for user inspection.
	ExecutePipeline(*PipelineExecuteRequest, Core_ExecutePipelineServer) error
	// Lists all pipelines in session.
	ListPipelines(context.Context, *PipelineListRequest) (*PipelineListResult, error)
	// Deletes specified pipelines in session, returns IDs of successfully deleted pipelines.
	DeletePipelines(context.Context, *PipelineDeleteRequest) (*PipelineListResult, error)
	// Cancels processing (creation or execution) of specified pipelines in session, but does not
	// delete.  Returns IDs of successfully canceled pipelines.  State of a canceled pipeline is
	// unspecified.  It could be useable or not.
	CancelPipelines(context.Context, *PipelineCancelRequest) (*PipelineListResult, error)
	// Obtain results; lists existing pipelines then streams new results as they become available.
	GetCreatePipelineResults(*PipelineCreateResultsRequest, Core_GetCreatePipelineResultsServer) error
	GetExecutePipelineResults(*PipelineExecuteResultsRequest, Core_GetExecutePipelineResultsServer) error
	// Export executable of a pipeline, including any optional preprocessing used in session.
	ExportPipeline(context.Context, *PipelineExportRequest) (*Response, error)
	// Set problem schema for current session.
	SetProblemDoc(context.Context, *SetProblemDocRequest) (*Response, error)
	// Session management.
	// Create a new user session, which provides a session context for creation and execution of pipelines.
	StartSession(context.Context, *SessionRequest) (*SessionResponse, error)
	// Terminate a user session and release associated context resources.
	EndSession(context.Context, *SessionContext) (*Response, error)
}

func RegisterCoreServer(s *grpc.Server, srv CoreServer) {
	s.RegisterService(&_Core_serviceDesc, srv)
}

func _Core_CreatePipelines_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineCreateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).CreatePipelines(m, &coreCreatePipelinesServer{stream})
}

type Core_CreatePipelinesServer interface {
	Send(*PipelineCreateResult) error
	grpc.ServerStream
}

type coreCreatePipelinesServer struct {
	grpc.ServerStream
}

func (x *coreCreatePipelinesServer) Send(m *PipelineCreateResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Core_ExecutePipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).ExecutePipeline(m, &coreExecutePipelineServer{stream})
}

type Core_ExecutePipelineServer interface {
	Send(*PipelineExecuteResult) error
	grpc.ServerStream
}

type coreExecutePipelineServer struct {
	grpc.ServerStream
}

func (x *coreExecutePipelineServer) Send(m *PipelineExecuteResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Core_ListPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ListPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/ListPipelines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ListPipelines(ctx, req.(*PipelineListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_DeletePipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).DeletePipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/DeletePipelines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).DeletePipelines(ctx, req.(*PipelineDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_CancelPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).CancelPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/CancelPipelines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).CancelPipelines(ctx, req.(*PipelineCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetCreatePipelineResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineCreateResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).GetCreatePipelineResults(m, &coreGetCreatePipelineResultsServer{stream})
}

type Core_GetCreatePipelineResultsServer interface {
	Send(*PipelineCreateResult) error
	grpc.ServerStream
}

type coreGetCreatePipelineResultsServer struct {
	grpc.ServerStream
}

func (x *coreGetCreatePipelineResultsServer) Send(m *PipelineCreateResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Core_GetExecutePipelineResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineExecuteResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).GetExecutePipelineResults(m, &coreGetExecutePipelineResultsServer{stream})
}

type Core_GetExecutePipelineResultsServer interface {
	Send(*PipelineExecuteResult) error
	grpc.ServerStream
}

type coreGetExecutePipelineResultsServer struct {
	grpc.ServerStream
}

func (x *coreGetExecutePipelineResultsServer) Send(m *PipelineExecuteResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Core_ExportPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ExportPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/ExportPipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ExportPipeline(ctx, req.(*PipelineExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_SetProblemDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProblemDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).SetProblemDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/SetProblemDoc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).SetProblemDoc(ctx, req.(*SetProblemDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/StartSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).StartSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/EndSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).EndSession(ctx, req.(*SessionContext))
	}
	return interceptor(ctx, in, info, handler)
}

var _Core_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPipelines",
			Handler:    _Core_ListPipelines_Handler,
		},
		{
			MethodName: "DeletePipelines",
			Handler:    _Core_DeletePipelines_Handler,
		},
		{
			MethodName: "CancelPipelines",
			Handler:    _Core_CancelPipelines_Handler,
		},
		{
			MethodName: "ExportPipeline",
			Handler:    _Core_ExportPipeline_Handler,
		},
		{
			MethodName: "SetProblemDoc",
			Handler:    _Core_SetProblemDoc_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _Core_StartSession_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _Core_EndSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreatePipelines",
			Handler:       _Core_CreatePipelines_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecutePipeline",
			Handler:       _Core_ExecutePipeline_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCreatePipelineResults",
			Handler:       _Core_GetCreatePipelineResults_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetExecutePipelineResults",
			Handler:       _Core_GetExecutePipelineResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core.proto",
}

func init() { proto.RegisterFile("core.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1922 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4b, 0x6f, 0xe3, 0xd6,
	0x15, 0xd6, 0xfb, 0x71, 0xf4, 0xa2, 0xaf, 0x1f, 0xa3, 0x38, 0xe3, 0x8c, 0x47, 0x59, 0xd4, 0x71,
	0x06, 0x9c, 0xb1, 0x06, 0x45, 0x81, 0xa2, 0x8b, 0xd0, 0xe4, 0x95, 0x7d, 0x3b, 0x14, 0xa9, 0x5e,
	0x92, 0xce, 0x4c, 0x36, 0x84, 0x46, 0xba, 0x36, 0x84, 0xc8, 0xa2, 0x4a, 0x52, 0x81, 0xb3, 0x28,
	0xd0, 0x4d, 0x36, 0xdd, 0x74, 0xd7, 0x1f, 0x50, 0xa0, 0xf9, 0x07, 0x45, 0x77, 0xdd, 0x76, 0x5f,
	0xf4, 0x0f, 0xf4, 0x9f, 0x14, 0xf7, 0x92, 0x94, 0x28, 0x59, 0x63, 0x34, 0x06, 0x06, 0xc8, 0xca,
	0x3e, 0xef, 0x73, 0xbe, 0x7b, 0x8e, 0xce, 0x91, 0x00, 0x46, 0x9e, 0xcf, 0xe4, 0xb9, 0xef, 0x85,
	0xde, 0xe1, 0xf1, 0x8d, 0xe7, 0xdd, 0x4c, 0xd9, 0x4b, 0x41, 0xbd, 0x5f, 0x5c, 0xbf, 0x1c, 0xb3,
	0x60, 0xe4, 0x4f, 0xe6, 0xa1, 0xe7, 0x47, 0x1a, 0x9d, 0x97, 0xd0, 0xb4, 0x58, 0x10, 0x4c, 0xbc,
	0x99, 0xea, 0xcd, 0x42, 0x76, 0x17, 0xa2, 0x23, 0x80, 0x20, 0xe2, 0xb8, 0x93, 0x71, 0x3b, 0x7b,
	0x9c, 0x3d, 0xa9, 0xd2, 0x6a, 0xcc, 0x21, 0xe3, 0x8e, 0x0a, 0x25, 0x2b, 0x1c, 0x86, 0x8b, 0x00,
	0x3d, 0x83, 0xc2, 0xc8, 0x1b, 0x33, 0xa1, 0xd2, 0xec, 0xd6, 0xe4, 0x88, 0xad, 0x7a, 0x63, 0x46,
	0x85, 0x00, 0xb5, 0xa1, 0x3c, 0x66, 0xe1, 0x70, 0x32, 0x0d, 0xda, 0x39, 0xe1, 0x26, 0x21, 0x3b,
	0x5f, 0x42, 0x85, 0xb2, 0x60, 0xee, 0xcd, 0x02, 0x86, 0x9e, 0x41, 0x29, 0x10, 0x96, 0xc2, 0x51,
	0xad, 0x5b, 0x8e, 0x1d, 0xd1, 0x98, 0xdd, 0x21, 0xcb, 0x14, 0x29, 0xfb, 0xfd, 0x82, 0x05, 0x22,
	0xc5, 0x45, 0xc0, 0x7c, 0x77, 0x78, 0xc3, 0x66, 0x61, 0x92, 0x22, 0xe7, 0x28, 0x9c, 0xc1, 0xe3,
	0x7e, 0xc7, 0x7c, 0x6e, 0x90, 0xc4, 0x8d, 0xc9, 0xce, 0xdf, 0xb2, 0xd0, 0x5a, 0xfa, 0x8a, 0xe3,
	0xcb, 0xd0, 0xf0, 0xe3, 0xff, 0xdd, 0xc9, 0xec, 0xda, 0x8b, 0xd3, 0xa8, 0xca, 0x89, 0x06, 0xad,
	0x27, 0x72, 0x32, 0xbb, 0xf6, 0x36, 0x82, 0xe7, 0x1e, 0x08, 0x9e, 0x5f, 0x0b, 0x8e, 0xbe, 0x80,
	0xf2, 0x28, 0xc2, 0xb8, 0x5d, 0x10, 0x21, 0x5a, 0xf2, 0x3a, 0xf4, 0x34, 0x91, 0x77, 0xfa, 0x50,
	0xee, 0xb1, 0x61, 0xb8, 0xf0, 0x39, 0x3c, 0x35, 0x9f, 0x05, 0xde, 0xc2, 0x1f, 0xb1, 0xd5, 0x7b,
	0x40, 0xc2, 0x22, 0x63, 0xf4, 0x1c, 0xea, 0xd7, 0x91, 0xae, 0x3b, 0x1b, 0xde, 0xb2, 0x38, 0xa3,
	0x5a, 0xcc, 0x33, 0x86, 0xb7, 0xac, 0xf3, 0xcf, 0x3c, 0xec, 0x0f, 0x26, 0x73, 0x36, 0x9d, 0xcc,
	0x98, 0xea, 0xb3, 0x61, 0xc8, 0x12, 0x24, 0x53, 0x39, 0x65, 0x1f, 0xce, 0x89, 0x27, 0x32, 0x1e,
	0x86, 0xc3, 0x80, 0x85, 0xee, 0xc2, 0x9f, 0xc4, 0x61, 0x20, 0x66, 0x39, 0xfe, 0x04, 0x1d, 0x41,
	0x21, 0x1c, 0x06, 0xdf, 0x8a, 0xb2, 0x9b, 0xdd, 0xaa, 0x6c, 0x0f, 0x83, 0x6f, 0xed, 0xef, 0xe7,
	0x8c, 0x0a, 0x36, 0x7a, 0x09, 0x75, 0xfe, 0xd7, 0x0d, 0x16, 0xef, 0xc3, 0xef, 0xe7, 0x4c, 0x60,
	0xd0, 0xec, 0xd6, 0x85, 0x9a, 0x15, 0xf1, 0x68, 0x2d, 0x5c, 0x11, 0xe8, 0x0b, 0x90, 0x84, 0x41,
	0xd2, 0xb3, 0x1c, 0xd2, 0xa2, 0x88, 0xda, 0xe2, 0x7c, 0x6d, 0xc5, 0x46, 0x9f, 0x43, 0xc9, 0x5b,
	0x84, 0xf3, 0x45, 0xd8, 0x2e, 0xc5, 0xcd, 0x68, 0x0a, 0x52, 0x84, 0x8f, 0x45, 0xe8, 0x05, 0x94,
	0x6f, 0x59, 0xe8, 0x4f, 0x46, 0x41, 0xbb, 0x7c, 0x9c, 0x3f, 0x69, 0x76, 0x91, 0x3c, 0x60, 0xfe,
	0xb5, 0xe7, 0xdf, 0x0e, 0x67, 0x23, 0xd6, 0x17, 0x22, 0x9a, 0xa8, 0xa0, 0x33, 0x68, 0x85, 0x43,
	0xff, 0x86, 0x85, 0x6e, 0x8c, 0x64, 0xd0, 0xae, 0x1c, 0xe7, 0x4f, 0x6a, 0xdd, 0x8a, 0x1c, 0x3f,
	0x0d, 0x6d, 0x46, 0x0a, 0x31, 0x19, 0xa0, 0xd7, 0x20, 0xcd, 0x7d, 0x36, 0x9e, 0x8c, 0x52, 0x36,
	0xd5, 0x0d, 0x9b, 0x56, 0xac, 0xb1, 0x34, 0xfa, 0x1c, 0x1a, 0xb7, 0xc3, 0x3b, 0x77, 0x1e, 0x3f,
	0x4f, 0xd0, 0x86, 0xe3, 0xec, 0x49, 0x91, 0xd6, 0x6f, 0x87, 0x77, 0xc9, 0x93, 0xf1, 0x11, 0x28,
	0x5a, 0x7c, 0xac, 0xd1, 0x29, 0x94, 0xa2, 0x04, 0xe3, 0xa9, 0xdb, 0x56, 0x42, 0xac, 0x81, 0xf6,
	0xa0, 0xf8, 0xdd, 0x70, 0xba, 0x88, 0x3a, 0x22, 0x47, 0x23, 0xa2, 0xf3, 0x07, 0xa8, 0x24, 0x7e,
	0xd1, 0x0b, 0x40, 0x49, 0xc2, 0x3e, 0x0b, 0x16, 0xd3, 0xe8, 0x65, 0xa3, 0x16, 0x4b, 0x4a, 0xa1,
	0x42, 0xc0, 0xdf, 0x77, 0x05, 0x72, 0xee, 0xc3, 0x20, 0x7f, 0x06, 0xa5, 0x80, 0x67, 0x1a, 0xb4,
	0xf3, 0xa2, 0xf2, 0x92, 0x2c, 0x12, 0xa7, 0x31, 0xb7, 0xf3, 0xaf, 0x2c, 0xec, 0x6d, 0xb6, 0x22,
	0x0f, 0xf0, 0x93, 0xc7, 0x50, 0x86, 0xc6, 0xdc, 0xf7, 0x6e, 0x7c, 0x16, 0x04, 0x91, 0x7e, 0x2e,
	0x6e, 0xbb, 0x41, 0xcc, 0xa5, 0xf5, 0x44, 0x2e, 0xf4, 0x9f, 0x41, 0x2d, 0xc1, 0x98, 0xcf, 0x51,
	0x34, 0x9b, 0x90, 0xb0, 0xc8, 0x58, 0x38, 0x5c, 0x2a, 0x70, 0x87, 0x85, 0x38, 0x81, 0x24, 0x5d,
	0x5a, 0x5f, 0x6a, 0xcf, 0xae, 0xbd, 0xce, 0x0f, 0x59, 0x38, 0x48, 0x44, 0xf8, 0x8e, 0x8d, 0x16,
	0x8f, 0x9d, 0xaa, 0x74, 0x5a, 0xb9, 0x7b, 0x69, 0x6d, 0x8c, 0x5d, 0x7e, 0x73, 0xec, 0x3a, 0xff,
	0xc8, 0xae, 0x86, 0x7b, 0x99, 0xc7, 0xcf, 0x03, 0xd2, 0x23, 0x80, 0x54, 0x5f, 0x15, 0xa2, 0x8f,
	0x4a, 0x3f, 0x69, 0xa8, 0xce, 0x57, 0xb0, 0x9b, 0x24, 0xae, 0x4f, 0x82, 0xf0, 0xa7, 0xa3, 0xd7,
	0xf1, 0x57, 0xa5, 0x6b, 0x6c, 0xca, 0x1e, 0xf5, 0x02, 0x32, 0xec, 0x8e, 0x85, 0xad, 0x9b, 0x2a,
	0x86, 0x6f, 0xac, 0xfc, 0x49, 0x95, 0xee, 0x44, 0xa2, 0xc1, 0xb2, 0xa6, 0x20, 0x1d, 0x53, 0xe5,
	0x53, 0x37, 0x7d, 0x5c, 0xcc, 0x91, 0xb0, 0xdd, 0x1a, 0x33, 0x12, 0xa5, 0x63, 0xde, 0x00, 0x5a,
	0x47, 0xea, 0x51, 0xef, 0xfb, 0x1c, 0xea, 0x5b, 0xc2, 0xd5, 0xe6, 0xa9, 0x40, 0x53, 0x78, 0xba,
	0x6d, 0x3a, 0x83, 0x47, 0xd4, 0xf8, 0x7f, 0x44, 0xbb, 0x85, 0xa3, 0xad, 0x9d, 0xfb, 0x91, 0xc2,
	0xfd, 0x79, 0x6d, 0x52, 0xe6, 0x9e, 0x1f, 0x7e, 0x8c, 0x81, 0x3d, 0x85, 0x9d, 0xa5, 0x02, 0xbb,
	0x63, 0xa3, 0xd4, 0xd8, 0xb6, 0xe6, 0xa9, 0x6a, 0xf9, 0x04, 0xfc, 0x25, 0x0f, 0x7b, 0x16, 0x0b,
	0x07, 0xbe, 0xf7, 0x7e, 0xca, 0x6e, 0x35, 0x6f, 0x94, 0x24, 0xd4, 0x83, 0xf2, 0x62, 0x3e, 0x1e,
	0x86, 0x8c, 0x5f, 0x45, 0xfc, 0x73, 0xf4, 0x85, 0xbc, 0x4d, 0x4f, 0xa6, 0x6c, 0x3e, 0x1d, 0x8e,
	0xd8, 0x4a, 0xd0, 0x9b, 0xb0, 0xe9, 0x98, 0x26, 0xc6, 0xe9, 0xc2, 0x72, 0x0f, 0x17, 0x76, 0xf8,
	0xa7, 0x1c, 0x1c, 0x6c, 0x77, 0x87, 0x4e, 0xa0, 0x2a, 0x36, 0xb1, 0xd8, 0xdb, 0xd9, 0x8d, 0xf5,
	0x7e, 0x99, 0xa1, 0x95, 0x30, 0xfe, 0x1f, 0x9d, 0x6d, 0x2c, 0xf9, 0xdc, 0xfd, 0x25, 0x7f, 0x99,
	0x59, 0x5f, 0xf3, 0x5f, 0x6e, 0x59, 0xf3, 0x02, 0xae, 0xcb, 0xcc, 0xfd, 0x45, 0x2f, 0x43, 0x2d,
	0x5a, 0x34, 0x6e, 0xea, 0x86, 0x48, 0x2f, 0xa2, 0xcb, 0x0c, 0x05, 0x6f, 0x49, 0xa1, 0x17, 0xcb,
	0x7d, 0x59, 0xfc, 0xd0, 0xbe, 0xbc, 0xcc, 0x24, 0x1b, 0xf3, 0xbc, 0x02, 0xa5, 0x08, 0xb8, 0xd3,
	0x1f, 0x72, 0x00, 0xab, 0x7b, 0x16, 0xd5, 0xa0, 0xec, 0x18, 0x6f, 0x0c, 0xf3, 0x6b, 0x43, 0xca,
	0xa0, 0x12, 0xe4, 0xcc, 0x37, 0x52, 0x16, 0x35, 0xa0, 0xaa, 0x2a, 0x86, 0x8a, 0x75, 0x1d, 0x6b,
	0x52, 0x0e, 0xed, 0x42, 0xcb, 0xc2, 0x96, 0x45, 0x4c, 0xc3, 0x4d, 0x74, 0xf3, 0x68, 0x07, 0x1a,
	0x09, 0x13, 0x1b, 0x1a, 0xd6, 0xa4, 0x42, 0x5a, 0x0f, 0xbf, 0x1d, 0x10, 0x8a, 0x35, 0xa9, 0x88,
	0xf6, 0x40, 0x22, 0xc6, 0x95, 0xa2, 0x13, 0xcd, 0x55, 0xe8, 0x85, 0xd3, 0xc7, 0x86, 0x2d, 0x95,
	0xd0, 0x01, 0x20, 0x8a, 0x2d, 0xd3, 0xa1, 0x2a, 0x76, 0xf1, 0xdb, 0x4b, 0xc5, 0xb1, 0x6c, 0xac,
	0x49, 0x65, 0xd4, 0x82, 0x9a, 0x63, 0x28, 0x57, 0x0a, 0xd1, 0x95, 0x73, 0x1d, 0x4b, 0x15, 0xf4,
	0x04, 0x76, 0x7b, 0x0a, 0xd1, 0xb1, 0xe6, 0x0e, 0x28, 0x56, 0x4d, 0x43, 0x23, 0x36, 0x31, 0x0d,
	0xa9, 0x8a, 0x24, 0xa8, 0x9b, 0x8e, 0xed, 0x9a, 0x3d, 0x97, 0x2a, 0xc6, 0x05, 0x96, 0x80, 0x67,
	0xe4, 0x18, 0xa4, 0x3f, 0xd0, 0x31, 0x0f, 0x82, 0x35, 0xa9, 0x86, 0xea, 0x50, 0x21, 0x86, 0x8d,
	0xa9, 0xa1, 0xe8, 0x52, 0x9d, 0xd7, 0xaa, 0x9c, 0x9b, 0x94, 0x8b, 0x1a, 0xa7, 0x0c, 0x2a, 0xc9,
	0x87, 0x3f, 0xcf, 0x71, 0x40, 0xcd, 0x0b, 0x8a, 0x2d, 0xcb, 0x5d, 0xa1, 0xd1, 0x80, 0xaa, 0xe5,
	0x9c, 0xf7, 0x89, 0xcd, 0x0d, 0xb2, 0xdc, 0x9a, 0x3a, 0x86, 0x41, 0x8c, 0x0b, 0x29, 0x27, 0x60,
	0x1b, 0x68, 0x0a, 0x97, 0xe4, 0x05, 0x5c, 0x26, 0x8f, 0x6b, 0x0b, 0x18, 0x6a, 0x50, 0xc6, 0x94,
	0x9a, 0xa2, 0xfc, 0xd3, 0x3f, 0xe6, 0xa0, 0x92, 0xf4, 0x13, 0x2f, 0xc6, 0x56, 0xac, 0x37, 0xae,
	0xfd, 0x6e, 0x80, 0x5d, 0xc7, 0xd0, 0x70, 0x8f, 0x18, 0x58, 0x93, 0x32, 0x08, 0x41, 0x53, 0xd5,
	0x15, 0xcb, 0x22, 0x3d, 0xa2, 0x2a, 0xa2, 0xc0, 0x2c, 0x6a, 0x02, 0x50, 0x2c, 0x72, 0xe2, 0x74,
	0x8e, 0xd3, 0xaa, 0xce, 0x71, 0xa2, 0x3c, 0x85, 0x3c, 0x47, 0x5b, 0x27, 0xc6, 0x1b, 0x8e, 0x8b,
	0x46, 0x54, 0x61, 0x54, 0x40, 0xfb, 0xb0, 0x73, 0x85, 0xa9, 0x8d, 0xdf, 0xba, 0x86, 0xd9, 0x27,
	0x46, 0xe4, 0xab, 0xc8, 0x03, 0xab, 0x66, 0xbf, 0xef, 0x18, 0xc4, 0x7e, 0xe7, 0x6a, 0xd8, 0xc6,
	0x91, 0x7e, 0x89, 0x57, 0x7e, 0x41, 0x95, 0xc1, 0xa5, 0x9b, 0x72, 0x5d, 0xe6, 0xe9, 0x44, 0xdc,
	0xbe, 0x62, 0xab, 0x97, 0x9c, 0x57, 0x41, 0x9f, 0xc2, 0x13, 0x9b, 0xf4, 0xb1, 0x6b, 0x61, 0x4a,
	0xb0, 0xe5, 0xf6, 0x4c, 0x8a, 0x55, 0xc5, 0xb2, 0xb9, 0xb0, 0xca, 0x85, 0xaa, 0xa9, 0xeb, 0x1c,
	0x5d, 0xc5, 0x26, 0x57, 0xd8, 0xed, 0x11, 0x3d, 0xf6, 0x06, 0xa7, 0x3f, 0x66, 0xa1, 0x96, 0x9a,
	0x12, 0x74, 0x08, 0x07, 0x02, 0x05, 0xcb, 0x39, 0xbf, 0x07, 0x44, 0x05, 0x0a, 0x86, 0x69, 0x60,
	0x29, 0x8b, 0x00, 0x4a, 0xe7, 0xc4, 0x50, 0xe8, 0xbb, 0xa8, 0xf4, 0xbe, 0xa3, 0xdb, 0x44, 0x60,
	0x24, 0xe5, 0x97, 0xb4, 0xae, 0x9c, 0x63, 0x5d, 0x2a, 0x70, 0xda, 0x31, 0xc8, 0x95, 0x42, 0x89,
	0x62, 0x63, 0xa9, 0xc8, 0x7b, 0x43, 0xc8, 0x13, 0x4e, 0x89, 0xf7, 0x95, 0x79, 0x85, 0xa9, 0xae,
	0x0c, 0x06, 0xcb, 0x12, 0x0d, 0xd3, 0x48, 0xf3, 0x2a, 0xa7, 0xbf, 0x00, 0x58, 0x8d, 0x1b, 0xfa,
	0x04, 0xf6, 0x4d, 0xc7, 0x1e, 0x38, 0xf6, 0xbd, 0xe7, 0x3a, 0xfd, 0x6f, 0x0e, 0x76, 0xee, 0x4d,
	0x1b, 0xc7, 0xb2, 0x8f, 0x6d, 0x4a, 0xd4, 0xcd, 0xa7, 0xc5, 0x6f, 0xb1, 0xea, 0x70, 0xc0, 0x5d,
	0x8e, 0xa0, 0x94, 0xe5, 0x6d, 0xa9, 0xa8, 0xaa, 0x43, 0x15, 0x95, 0x57, 0x57, 0x82, 0x5c, 0xef,
	0x4c, 0xca, 0x73, 0x6e, 0xef, 0xcc, 0xed, 0x13, 0x95, 0x9a, 0x52, 0x21, 0xa1, 0x14, 0x4e, 0x15,
	0x45, 0xf3, 0x99, 0xaa, 0xab, 0x38, 0xaa, 0x54, 0xe2, 0x8d, 0x1e, 0x13, 0xb1, 0x76, 0x79, 0x8d,
	0x25, 0x4c, 0x2a, 0x7c, 0xc4, 0xfa, 0x58, 0x31, 0x5c, 0xeb, 0x77, 0x8e, 0x42, 0xb1, 0xe6, 0x8a,
	0x9e, 0x8c, 0xde, 0x8a, 0x9a, 0xa6, 0xed, 0x6e, 0x11, 0x02, 0x7a, 0x06, 0x9f, 0x7e, 0x40, 0xe8,
	0x2a, 0x57, 0x17, 0x52, 0x8d, 0x77, 0x92, 0x90, 0x29, 0xe7, 0x96, 0xa9, 0x3b, 0x36, 0x8e, 0x2d,
	0xeb, 0x7c, 0x08, 0x68, 0x62, 0x21, 0x35, 0xd0, 0x73, 0x38, 0x32, 0x4c, 0xda, 0x57, 0x74, 0xf2,
	0x0d, 0xd6, 0xdc, 0xbe, 0x63, 0x3b, 0x8a, 0xee, 0x12, 0xa3, 0xc7, 0x79, 0xa2, 0xf7, 0x9a, 0xe8,
	0x29, 0xb4, 0x7f, 0xab, 0xa8, 0xaa, 0x42, 0x35, 0xd7, 0x22, 0x7d, 0xa2, 0x2b, 0x94, 0x77, 0xa7,
	0xa5, 0x9a, 0x14, 0x4b, 0xad, 0xee, 0xbf, 0x8b, 0x50, 0x50, 0xf9, 0x17, 0x03, 0x0d, 0x5a, 0xd1,
	0xc2, 0x5e, 0x7e, 0x69, 0x40, 0x07, 0xf2, 0xd6, 0xef, 0x7c, 0x87, 0xfb, 0xf2, 0xb6, 0x15, 0xdf,
	0xc9, 0xbc, 0xca, 0xa2, 0x1e, 0xb4, 0xe2, 0x45, 0xbc, 0xfc, 0x8e, 0xf0, 0x44, 0xde, 0x7e, 0xe4,
	0x1e, 0x1e, 0xc8, 0x5b, 0x77, 0xb7, 0xf0, 0xf3, 0x1b, 0x68, 0xf0, 0x3b, 0x65, 0x95, 0xcb, 0x9e,
	0xbc, 0xe5, 0xd2, 0x3b, 0xdc, 0x95, 0xef, 0x5f, 0x35, 0x9d, 0x0c, 0xfa, 0x0a, 0x5a, 0xda, 0xda,
	0xd9, 0x95, 0xae, 0x65, 0xed, 0xce, 0x7b, 0xc0, 0x83, 0xba, 0x76, 0x44, 0xad, 0xa1, 0x91, 0xbe,
	0xda, 0x3e, 0xe4, 0xc1, 0x86, 0xf6, 0x05, 0x0b, 0xd7, 0x21, 0x8d, 0x8f, 0x13, 0x74, 0x24, 0x3f,
	0x74, 0x23, 0x3d, 0x84, 0xef, 0xd7, 0xf0, 0xc9, 0x05, 0x0b, 0x37, 0x20, 0x4e, 0xdc, 0x7e, 0x26,
	0x3f, 0x78, 0x0c, 0x3d, 0x08, 0xf8, 0x2f, 0xa1, 0x19, 0x5d, 0x34, 0xcb, 0x77, 0x4b, 0x6b, 0xa7,
	0x4e, 0x9d, 0xc3, 0xd5, 0x75, 0xd8, 0xc9, 0xa0, 0xd7, 0xd0, 0x58, 0x3b, 0x2b, 0xd0, 0xfe, 0xd6,
	0x33, 0x63, 0xd3, 0xa8, 0x6e, 0x85, 0x43, 0x3f, 0x8c, 0x0f, 0x09, 0xb4, 0x3c, 0x29, 0x12, 0x6d,
	0x49, 0xde, 0xf8, 0x8d, 0xa5, 0x93, 0x41, 0xa7, 0x00, 0x78, 0x36, 0xbe, 0x67, 0x12, 0x5f, 0x21,
	0x6b, 0x01, 0x7e, 0x4d, 0xf8, 0xf7, 0x68, 0x2f, 0xf4, 0x46, 0xde, 0xd4, 0x4d, 0x7e, 0x3c, 0x79,
	0x2a, 0x47, 0x3f, 0x65, 0xc9, 0xc9, 0x4f, 0x59, 0x72, 0x6f, 0x32, 0x65, 0xa6, 0xb8, 0x0a, 0x82,
	0xf6, 0x7f, 0x7e, 0x4c, 0x0e, 0xac, 0xd8, 0xee, 0x2a, 0x32, 0x3b, 0x6f, 0xff, 0xf5, 0xef, 0x87,
	0xd0, 0x7d, 0x75, 0xf6, 0x2b, 0xf9, 0xac, 0x2b, 0x77, 0x5f, 0x7d, 0x53, 0x49, 0x2e, 0xb0, 0xf7,
	0x25, 0xa1, 0xfa, 0xfa, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x42, 0x98, 0x1a, 0x60, 0x2f, 0x13,
	0x00, 0x00,
}
