// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pipeline_service.proto

/*
Package pipeline is a generated protocol buffer package.

It is generated from these files:
	pipeline_service.proto

It has these top-level messages:
	SessionContext
	Status
	Response
	SessionRequest
	PipelineCreateRequest
	Score
	PipelineCreated
	PipelineCreateResult
	PipelineExecuteRequest
	PipelineExecuteResult
*/
package pipeline

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_OK                  StatusCode = 0
	StatusCode_CANCELLED           StatusCode = 1
	StatusCode_INVALID_ARGUMENT    StatusCode = 2
	StatusCode_RESOURCE_EXHAUSTED  StatusCode = 3
	StatusCode_UNAVAILABLE         StatusCode = 4
	StatusCode_FAILED_PRECONDITION StatusCode = 5
	StatusCode_OUT_OF_RANGE        StatusCode = 6
	StatusCode_UNIMPLEMENTED       StatusCode = 7
	StatusCode_INTERNAL            StatusCode = 8
	StatusCode_ABORTED             StatusCode = 9
	StatusCode_UNKNOWN             StatusCode = 10
)

var StatusCode_name = map[int32]string{
	0:  "OK",
	1:  "CANCELLED",
	2:  "INVALID_ARGUMENT",
	3:  "RESOURCE_EXHAUSTED",
	4:  "UNAVAILABLE",
	5:  "FAILED_PRECONDITION",
	6:  "OUT_OF_RANGE",
	7:  "UNIMPLEMENTED",
	8:  "INTERNAL",
	9:  "ABORTED",
	10: "UNKNOWN",
}
var StatusCode_value = map[string]int32{
	"OK":                  0,
	"CANCELLED":           1,
	"INVALID_ARGUMENT":    2,
	"RESOURCE_EXHAUSTED":  3,
	"UNAVAILABLE":         4,
	"FAILED_PRECONDITION": 5,
	"OUT_OF_RANGE":        6,
	"UNIMPLEMENTED":       7,
	"INTERNAL":            8,
	"ABORTED":             9,
	"UNKNOWN":             10,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Progress int32

const (
	Progress_SUBMITTED Progress = 0
	Progress_RUNNING   Progress = 1
	Progress_COMPLETE  Progress = 2
)

var Progress_name = map[int32]string{
	0: "SUBMITTED",
	1: "RUNNING",
	2: "COMPLETE",
}
var Progress_value = map[string]int32{
	"SUBMITTED": 0,
	"RUNNING":   1,
	"COMPLETE":  2,
}

func (x Progress) String() string {
	return proto.EnumName(Progress_name, int32(x))
}
func (Progress) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Task int32

const (
	Task_CLASSIFICATION Task = 0
	Task_REGRESSION     Task = 1
)

var Task_name = map[int32]string{
	0: "CLASSIFICATION",
	1: "REGRESSION",
}
var Task_value = map[string]int32{
	"CLASSIFICATION": 0,
	"REGRESSION":     1,
}

func (x Task) String() string {
	return proto.EnumName(Task_name, int32(x))
}
func (Task) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Output int32

const (
	Output_CLASS_LABEL      Output = 0
	Output_PROBABILITY      Output = 1
	Output_GENERAL_SCORE    Output = 2
	Output_MULTILABEL       Output = 3
	Output_REGRESSION_VALUE Output = 4
)

var Output_name = map[int32]string{
	0: "CLASS_LABEL",
	1: "PROBABILITY",
	2: "GENERAL_SCORE",
	3: "MULTILABEL",
	4: "REGRESSION_VALUE",
}
var Output_value = map[string]int32{
	"CLASS_LABEL":      0,
	"PROBABILITY":      1,
	"GENERAL_SCORE":    2,
	"MULTILABEL":       3,
	"REGRESSION_VALUE": 4,
}

func (x Output) String() string {
	return proto.EnumName(Output_name, int32(x))
}
func (Output) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Metric int32

const (
	Metric_ACCURACY              Metric = 0
	Metric_PRECISION             Metric = 1
	Metric_RECALL                Metric = 2
	Metric_F1_MICRO              Metric = 4
	Metric_F1_MACRO              Metric = 5
	Metric_ROC_AUC               Metric = 6
	Metric_LOG_LOSS              Metric = 7
	Metric_MEAN_SQUARED_ERR      Metric = 8
	Metric_ROOT_MEAN_SQUARED_ERR Metric = 9
	Metric_MEAN_ABSOLUTE_ERR     Metric = 10
	Metric_MEDIAN_ABSOSLUTE_ERR  Metric = 11
	Metric_R2                    Metric = 12
)

var Metric_name = map[int32]string{
	0:  "ACCURACY",
	1:  "PRECISION",
	2:  "RECALL",
	4:  "F1_MICRO",
	5:  "F1_MACRO",
	6:  "ROC_AUC",
	7:  "LOG_LOSS",
	8:  "MEAN_SQUARED_ERR",
	9:  "ROOT_MEAN_SQUARED_ERR",
	10: "MEAN_ABSOLUTE_ERR",
	11: "MEDIAN_ABSOSLUTE_ERR",
	12: "R2",
}
var Metric_value = map[string]int32{
	"ACCURACY":              0,
	"PRECISION":             1,
	"RECALL":                2,
	"F1_MICRO":              4,
	"F1_MACRO":              5,
	"ROC_AUC":               6,
	"LOG_LOSS":              7,
	"MEAN_SQUARED_ERR":      8,
	"ROOT_MEAN_SQUARED_ERR": 9,
	"MEAN_ABSOLUTE_ERR":     10,
	"MEDIAN_ABSOSLUTE_ERR":  11,
	"R2": 12,
}

func (x Metric) String() string {
	return proto.EnumName(Metric_name, int32(x))
}
func (Metric) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SessionContext struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *SessionContext) Reset()                    { *m = SessionContext{} }
func (m *SessionContext) String() string            { return proto.CompactTextString(m) }
func (*SessionContext) ProtoMessage()               {}
func (*SessionContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SessionContext) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type Status struct {
	Code    StatusCode `protobuf:"varint,1,opt,name=code,enum=pipeline.StatusCode" json:"code,omitempty"`
	Details string     `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Status) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_OK
}

func (m *Status) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type Response struct {
	Context *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	Status  *Status         `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Response) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type SessionRequest struct {
}

func (m *SessionRequest) Reset()                    { *m = SessionRequest{} }
func (m *SessionRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()               {}
func (*SessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type PipelineCreateRequest struct {
	Context *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	// could also split into train_dataset_uri, train_targets_uri if training data left unjoined, would
	// make 'target_features' field redundant in that case
	TrainDatasetUris []string `protobuf:"bytes,2,rep,name=train_dataset_uris,json=trainDatasetUris" json:"train_dataset_uris,omitempty"`
	Task             Task     `protobuf:"varint,3,opt,name=task,enum=pipeline.Task" json:"task,omitempty"`
	Output           Output   `protobuf:"varint,4,opt,name=output,enum=pipeline.Output" json:"output,omitempty"`
	Metric           []Metric `protobuf:"varint,5,rep,packed,name=metric,enum=pipeline.Metric" json:"metric,omitempty"`
	TargetFeatures   []string `protobuf:"bytes,6,rep,name=target_features,json=targetFeatures" json:"target_features,omitempty"`
	MaxPipelines     int32    `protobuf:"varint,7,opt,name=max_pipelines,json=maxPipelines" json:"max_pipelines,omitempty"`
}

func (m *PipelineCreateRequest) Reset()                    { *m = PipelineCreateRequest{} }
func (m *PipelineCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineCreateRequest) ProtoMessage()               {}
func (*PipelineCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PipelineCreateRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineCreateRequest) GetTrainDatasetUris() []string {
	if m != nil {
		return m.TrainDatasetUris
	}
	return nil
}

func (m *PipelineCreateRequest) GetTask() Task {
	if m != nil {
		return m.Task
	}
	return Task_CLASSIFICATION
}

func (m *PipelineCreateRequest) GetOutput() Output {
	if m != nil {
		return m.Output
	}
	return Output_CLASS_LABEL
}

func (m *PipelineCreateRequest) GetMetric() []Metric {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *PipelineCreateRequest) GetTargetFeatures() []string {
	if m != nil {
		return m.TargetFeatures
	}
	return nil
}

func (m *PipelineCreateRequest) GetMaxPipelines() int32 {
	if m != nil {
		return m.MaxPipelines
	}
	return 0
}

type Score struct {
	Metric Metric  `protobuf:"varint,1,opt,name=metric,enum=pipeline.Metric" json:"metric,omitempty"`
	Value  float32 `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
}

func (m *Score) Reset()                    { *m = Score{} }
func (m *Score) String() string            { return proto.CompactTextString(m) }
func (*Score) ProtoMessage()               {}
func (*Score) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Score) GetMetric() Metric {
	if m != nil {
		return m.Metric
	}
	return Metric_ACCURACY
}

func (m *Score) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PipelineCreated struct {
	PredictResultUris []string `protobuf:"bytes,1,rep,name=predict_result_uris,json=predictResultUris" json:"predict_result_uris,omitempty"`
	Output            Output   `protobuf:"varint,2,opt,name=output,enum=pipeline.Output" json:"output,omitempty"`
	Score             []*Score `protobuf:"bytes,3,rep,name=score" json:"score,omitempty"`
}

func (m *PipelineCreated) Reset()                    { *m = PipelineCreated{} }
func (m *PipelineCreated) String() string            { return proto.CompactTextString(m) }
func (*PipelineCreated) ProtoMessage()               {}
func (*PipelineCreated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PipelineCreated) GetPredictResultUris() []string {
	if m != nil {
		return m.PredictResultUris
	}
	return nil
}

func (m *PipelineCreated) GetOutput() Output {
	if m != nil {
		return m.Output
	}
	return Output_CLASS_LABEL
}

func (m *PipelineCreated) GetScore() []*Score {
	if m != nil {
		return m.Score
	}
	return nil
}

type PipelineCreateResult struct {
	ResponseInfo *Response `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	ProgressInfo Progress  `protobuf:"varint,2,opt,name=progress_info,json=progressInfo,enum=pipeline.Progress" json:"progress_info,omitempty"`
	PipelineId   string    `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	// Will be set if progress info is a value other than COMPLETE
	PipelineInfo *PipelineCreated `protobuf:"bytes,4,opt,name=pipelineInfo" json:"pipelineInfo,omitempty"`
}

func (m *PipelineCreateResult) Reset()                    { *m = PipelineCreateResult{} }
func (m *PipelineCreateResult) String() string            { return proto.CompactTextString(m) }
func (*PipelineCreateResult) ProtoMessage()               {}
func (*PipelineCreateResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *PipelineCreateResult) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *PipelineCreateResult) GetProgressInfo() Progress {
	if m != nil {
		return m.ProgressInfo
	}
	return Progress_SUBMITTED
}

func (m *PipelineCreateResult) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineCreateResult) GetPipelineInfo() *PipelineCreated {
	if m != nil {
		return m.PipelineInfo
	}
	return nil
}

type PipelineExecuteRequest struct {
	Context            *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	PipelineId         string          `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	PredictDatasetUris []string        `protobuf:"bytes,3,rep,name=predict_dataset_uris,json=predictDatasetUris" json:"predict_dataset_uris,omitempty"`
}

func (m *PipelineExecuteRequest) Reset()                    { *m = PipelineExecuteRequest{} }
func (m *PipelineExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineExecuteRequest) ProtoMessage()               {}
func (*PipelineExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PipelineExecuteRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineExecuteRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineExecuteRequest) GetPredictDatasetUris() []string {
	if m != nil {
		return m.PredictDatasetUris
	}
	return nil
}

type PipelineExecuteResult struct {
	ResponseInfo *Response `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	ProgressInfo Progress  `protobuf:"varint,2,opt,name=progress_info,json=progressInfo,enum=pipeline.Progress" json:"progress_info,omitempty"`
	PipelineId   string    `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	// Will be set if progress info is a value other than COMPLETE
	ResultUris []string `protobuf:"bytes,4,rep,name=result_uris,json=resultUris" json:"result_uris,omitempty"`
}

func (m *PipelineExecuteResult) Reset()                    { *m = PipelineExecuteResult{} }
func (m *PipelineExecuteResult) String() string            { return proto.CompactTextString(m) }
func (*PipelineExecuteResult) ProtoMessage()               {}
func (*PipelineExecuteResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PipelineExecuteResult) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *PipelineExecuteResult) GetProgressInfo() Progress {
	if m != nil {
		return m.ProgressInfo
	}
	return Progress_SUBMITTED
}

func (m *PipelineExecuteResult) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineExecuteResult) GetResultUris() []string {
	if m != nil {
		return m.ResultUris
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionContext)(nil), "pipeline.SessionContext")
	proto.RegisterType((*Status)(nil), "pipeline.Status")
	proto.RegisterType((*Response)(nil), "pipeline.Response")
	proto.RegisterType((*SessionRequest)(nil), "pipeline.SessionRequest")
	proto.RegisterType((*PipelineCreateRequest)(nil), "pipeline.PipelineCreateRequest")
	proto.RegisterType((*Score)(nil), "pipeline.Score")
	proto.RegisterType((*PipelineCreated)(nil), "pipeline.PipelineCreated")
	proto.RegisterType((*PipelineCreateResult)(nil), "pipeline.PipelineCreateResult")
	proto.RegisterType((*PipelineExecuteRequest)(nil), "pipeline.PipelineExecuteRequest")
	proto.RegisterType((*PipelineExecuteResult)(nil), "pipeline.PipelineExecuteResult")
	proto.RegisterEnum("pipeline.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("pipeline.Progress", Progress_name, Progress_value)
	proto.RegisterEnum("pipeline.Task", Task_name, Task_value)
	proto.RegisterEnum("pipeline.Output", Output_name, Output_value)
	proto.RegisterEnum("pipeline.Metric", Metric_name, Metric_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PipelineCompute service

type PipelineComputeClient interface {
	// Train step - multiple result messages returned via GRPC streaming.
	CreatePipelines(ctx context.Context, in *PipelineCreateRequest, opts ...grpc.CallOption) (PipelineCompute_CreatePipelinesClient, error)
	// Predict step - multiple results messages returned via GRPC streaming.
	ExecutePipeline(ctx context.Context, in *PipelineExecuteRequest, opts ...grpc.CallOption) (PipelineCompute_ExecutePipelineClient, error)
	// Session management
	StartSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*Response, error)
	EndSession(ctx context.Context, in *SessionContext, opts ...grpc.CallOption) (*Response, error)
}

type pipelineComputeClient struct {
	cc *grpc.ClientConn
}

func NewPipelineComputeClient(cc *grpc.ClientConn) PipelineComputeClient {
	return &pipelineComputeClient{cc}
}

func (c *pipelineComputeClient) CreatePipelines(ctx context.Context, in *PipelineCreateRequest, opts ...grpc.CallOption) (PipelineCompute_CreatePipelinesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PipelineCompute_serviceDesc.Streams[0], c.cc, "/pipeline.PipelineCompute/CreatePipelines", opts...)
	if err != nil {
		return nil, err
	}
	x := &pipelineComputeCreatePipelinesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PipelineCompute_CreatePipelinesClient interface {
	Recv() (*PipelineCreateResult, error)
	grpc.ClientStream
}

type pipelineComputeCreatePipelinesClient struct {
	grpc.ClientStream
}

func (x *pipelineComputeCreatePipelinesClient) Recv() (*PipelineCreateResult, error) {
	m := new(PipelineCreateResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pipelineComputeClient) ExecutePipeline(ctx context.Context, in *PipelineExecuteRequest, opts ...grpc.CallOption) (PipelineCompute_ExecutePipelineClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PipelineCompute_serviceDesc.Streams[1], c.cc, "/pipeline.PipelineCompute/ExecutePipeline", opts...)
	if err != nil {
		return nil, err
	}
	x := &pipelineComputeExecutePipelineClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PipelineCompute_ExecutePipelineClient interface {
	Recv() (*PipelineExecuteResult, error)
	grpc.ClientStream
}

type pipelineComputeExecutePipelineClient struct {
	grpc.ClientStream
}

func (x *pipelineComputeExecutePipelineClient) Recv() (*PipelineExecuteResult, error) {
	m := new(PipelineExecuteResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pipelineComputeClient) StartSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pipeline.PipelineCompute/StartSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineComputeClient) EndSession(ctx context.Context, in *SessionContext, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pipeline.PipelineCompute/EndSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PipelineCompute service

type PipelineComputeServer interface {
	// Train step - multiple result messages returned via GRPC streaming.
	CreatePipelines(*PipelineCreateRequest, PipelineCompute_CreatePipelinesServer) error
	// Predict step - multiple results messages returned via GRPC streaming.
	ExecutePipeline(*PipelineExecuteRequest, PipelineCompute_ExecutePipelineServer) error
	// Session management
	StartSession(context.Context, *SessionRequest) (*Response, error)
	EndSession(context.Context, *SessionContext) (*Response, error)
}

func RegisterPipelineComputeServer(s *grpc.Server, srv PipelineComputeServer) {
	s.RegisterService(&_PipelineCompute_serviceDesc, srv)
}

func _PipelineCompute_CreatePipelines_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineCreateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PipelineComputeServer).CreatePipelines(m, &pipelineComputeCreatePipelinesServer{stream})
}

type PipelineCompute_CreatePipelinesServer interface {
	Send(*PipelineCreateResult) error
	grpc.ServerStream
}

type pipelineComputeCreatePipelinesServer struct {
	grpc.ServerStream
}

func (x *pipelineComputeCreatePipelinesServer) Send(m *PipelineCreateResult) error {
	return x.ServerStream.SendMsg(m)
}

func _PipelineCompute_ExecutePipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PipelineComputeServer).ExecutePipeline(m, &pipelineComputeExecutePipelineServer{stream})
}

type PipelineCompute_ExecutePipelineServer interface {
	Send(*PipelineExecuteResult) error
	grpc.ServerStream
}

type pipelineComputeExecutePipelineServer struct {
	grpc.ServerStream
}

func (x *pipelineComputeExecutePipelineServer) Send(m *PipelineExecuteResult) error {
	return x.ServerStream.SendMsg(m)
}

func _PipelineCompute_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineComputeServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pipeline.PipelineCompute/StartSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineComputeServer).StartSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineCompute_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineComputeServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pipeline.PipelineCompute/EndSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineComputeServer).EndSession(ctx, req.(*SessionContext))
	}
	return interceptor(ctx, in, info, handler)
}

var _PipelineCompute_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pipeline.PipelineCompute",
	HandlerType: (*PipelineComputeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _PipelineCompute_StartSession_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _PipelineCompute_EndSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreatePipelines",
			Handler:       _PipelineCompute_CreatePipelines_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecutePipeline",
			Handler:       _PipelineCompute_ExecutePipeline_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pipeline_service.proto",
}

func init() { proto.RegisterFile("pipeline_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1075 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0x8e, 0xf3, 0x3f, 0x27, 0x69, 0x32, 0x3b, 0x9b, 0xed, 0x2f, 0xbb, 0xd2, 0x8f, 0x56, 0x46,
	0x88, 0x28, 0x42, 0x65, 0x09, 0x48, 0xdc, 0x00, 0xd2, 0xc4, 0x99, 0x06, 0x6b, 0x1d, 0xbb, 0x8c,
	0xed, 0xb2, 0x7b, 0x65, 0x99, 0x64, 0xba, 0x58, 0xdb, 0xc6, 0xc1, 0x9e, 0xac, 0xfa, 0x1c, 0xbc,
	0x00, 0x8f, 0x82, 0xb8, 0x43, 0xe2, 0x8e, 0xa7, 0xe0, 0x31, 0xd0, 0x8c, 0xed, 0xfc, 0x69, 0xb7,
	0x20, 0xc1, 0x0d, 0x97, 0x73, 0xbe, 0xef, 0x7c, 0xfe, 0xe6, 0xcc, 0x39, 0x47, 0x86, 0xe3, 0x75,
	0xb4, 0xe6, 0xd7, 0xd1, 0x8a, 0x07, 0x29, 0x4f, 0xde, 0x46, 0x0b, 0x7e, 0xb6, 0x4e, 0x62, 0x11,
	0xe3, 0x66, 0x11, 0xd7, 0x3f, 0x86, 0xae, 0xcb, 0xd3, 0x34, 0x8a, 0x57, 0x46, 0xbc, 0x12, 0xfc,
	0x56, 0xe0, 0xff, 0x03, 0xa4, 0x59, 0x24, 0x88, 0x96, 0x03, 0xed, 0x54, 0x1b, 0xb6, 0x58, 0x2b,
	0x8f, 0x98, 0x4b, 0xdd, 0x82, 0xba, 0x2b, 0x42, 0xb1, 0x49, 0xf1, 0x10, 0xaa, 0x8b, 0x78, 0xc9,
	0x15, 0xa5, 0x3b, 0xee, 0x9f, 0x15, 0x9a, 0x67, 0x19, 0x6e, 0xc4, 0x4b, 0xce, 0x14, 0x03, 0x0f,
	0xa0, 0xb1, 0xe4, 0x22, 0x8c, 0xae, 0xd3, 0x41, 0x59, 0xe9, 0x15, 0x47, 0xfd, 0x7b, 0x68, 0x32,
	0x9e, 0xae, 0xe3, 0x55, 0xca, 0xf1, 0x18, 0x1a, 0x8b, 0xcc, 0x83, 0x92, 0x6c, 0x8f, 0x07, 0x7b,
	0x92, 0x07, 0x1e, 0x59, 0x41, 0xc4, 0x43, 0xa8, 0xa7, 0xea, 0x6b, 0x4a, 0xb8, 0x3d, 0x46, 0x77,
	0x5d, 0xb0, 0x1c, 0xd7, 0xd1, 0xf6, 0xa2, 0x8c, 0xff, 0xb0, 0xe1, 0xa9, 0xd0, 0x7f, 0x2e, 0xc3,
	0x93, 0x8b, 0x9c, 0x6d, 0x24, 0x3c, 0x14, 0x3c, 0x47, 0xfe, 0x91, 0x93, 0x8f, 0x00, 0x8b, 0x24,
	0x8c, 0x56, 0xc1, 0x32, 0x14, 0x61, 0xca, 0x45, 0xb0, 0x49, 0x22, 0xe9, 0xaa, 0x32, 0x6c, 0x31,
	0xa4, 0x90, 0x69, 0x06, 0xf8, 0x49, 0x94, 0x62, 0x1d, 0xaa, 0x22, 0x4c, 0xdf, 0x0c, 0x2a, 0xaa,
	0x76, 0xdd, 0x9d, 0xbc, 0x17, 0xa6, 0x6f, 0x98, 0xc2, 0xe4, 0xdd, 0xe2, 0x8d, 0x58, 0x6f, 0xc4,
	0xa0, 0xaa, 0x58, 0x7b, 0x77, 0x73, 0x54, 0x9c, 0xe5, 0xb8, 0x64, 0xde, 0x70, 0x91, 0x44, 0x8b,
	0x41, 0xed, 0xb4, 0x72, 0xc8, 0x9c, 0xab, 0x38, 0xcb, 0x71, 0xfc, 0x21, 0xf4, 0x44, 0x98, 0xbc,
	0xe6, 0x22, 0xb8, 0xe2, 0xa1, 0xd8, 0x24, 0x3c, 0x1d, 0xd4, 0x95, 0xc5, 0x6e, 0x16, 0x3e, 0xcf,
	0xa3, 0xf8, 0x7d, 0x38, 0xba, 0x09, 0x6f, 0x83, 0x42, 0x27, 0x1d, 0x34, 0x4e, 0xb5, 0x61, 0x8d,
	0x75, 0x6e, 0xc2, 0xdb, 0xa2, 0x66, 0xa9, 0x3e, 0x83, 0x9a, 0xbb, 0x88, 0x13, 0xbe, 0x67, 0x40,
	0xbb, 0x6b, 0xf5, 0x8e, 0x81, 0x3e, 0xd4, 0xde, 0x86, 0xd7, 0x1b, 0xae, 0xde, 0xab, 0xcc, 0xb2,
	0x83, 0xfe, 0xa3, 0x06, 0xbd, 0xc3, 0xa7, 0x58, 0xe2, 0x33, 0x78, 0xbc, 0x4e, 0xf8, 0x32, 0x5a,
	0x88, 0x20, 0xe1, 0xe9, 0xe6, 0x3a, 0xaf, 0xa8, 0xa6, 0xec, 0x3e, 0xca, 0x21, 0xa6, 0x10, 0x55,
	0xd2, 0x5d, 0xb9, 0xca, 0x7f, 0x53, 0xae, 0x0f, 0xa0, 0x96, 0x4a, 0xdb, 0x83, 0xca, 0x69, 0x65,
	0xd8, 0x1e, 0xf7, 0xf6, 0x1e, 0x57, 0x86, 0x59, 0x86, 0xea, 0x7f, 0x68, 0xd0, 0xbf, 0xdb, 0x1f,
	0xf2, 0x6b, 0xf8, 0x73, 0x38, 0x4a, 0xf2, 0xa6, 0x0d, 0xa2, 0xd5, 0x55, 0x9c, 0x37, 0x09, 0xde,
	0xe9, 0x14, 0x3d, 0xcd, 0x3a, 0x05, 0xd1, 0x5c, 0x5d, 0xc5, 0x32, 0x71, 0x9d, 0xc4, 0xaf, 0x13,
	0x9e, 0xa6, 0x59, 0x62, 0xe6, 0x74, 0x2f, 0xf1, 0x22, 0x87, 0x59, 0xa7, 0x20, 0xaa, 0xc4, 0x13,
	0x68, 0x6f, 0x27, 0x39, 0x5a, 0xaa, 0xae, 0x69, 0x31, 0x28, 0x42, 0xe6, 0x12, 0x7f, 0x09, 0x9d,
	0xed, 0x49, 0x0a, 0x57, 0x95, 0xa3, 0xa7, 0x7b, 0xc2, 0x87, 0xd5, 0x65, 0x07, 0x74, 0xfd, 0x27,
	0x0d, 0x8e, 0x0b, 0x06, 0xbd, 0xe5, 0x8b, 0xcd, 0xbf, 0x9b, 0x85, 0x3b, 0x76, 0xcb, 0xf7, 0xec,
	0x3e, 0x87, 0x7e, 0xf1, 0xb6, 0x07, 0xe3, 0x52, 0x51, 0x8f, 0x8b, 0x73, 0x6c, 0x6f, 0x60, 0xf4,
	0xdf, 0xb4, 0xdd, 0xb0, 0x6e, 0x1d, 0xfe, 0x57, 0x5f, 0xe3, 0x04, 0xda, 0xfb, 0x2d, 0x5b, 0x55,
	0xb7, 0x82, 0x64, 0xdb, 0xab, 0xa3, 0x5f, 0x35, 0x80, 0xdd, 0x96, 0xc4, 0x75, 0x28, 0x3b, 0x2f,
	0x50, 0x09, 0x1f, 0x41, 0xcb, 0x20, 0xb6, 0x41, 0x2d, 0x8b, 0x4e, 0x91, 0x86, 0xfb, 0x80, 0x4c,
	0xfb, 0x92, 0x58, 0xe6, 0x34, 0x20, 0x6c, 0xe6, 0xcf, 0xa9, 0xed, 0xa1, 0x32, 0x3e, 0x06, 0xcc,
	0xa8, 0xeb, 0xf8, 0xcc, 0xa0, 0x01, 0x7d, 0xf9, 0x35, 0xf1, 0x5d, 0x8f, 0x4e, 0x51, 0x05, 0xf7,
	0xa0, 0xed, 0xdb, 0xe4, 0x92, 0x98, 0x16, 0x99, 0x58, 0x14, 0x55, 0xf1, 0xff, 0xe0, 0xf1, 0x39,
	0x31, 0x2d, 0x3a, 0x0d, 0x2e, 0x18, 0x35, 0x1c, 0x7b, 0x6a, 0x7a, 0xa6, 0x63, 0xa3, 0x1a, 0x46,
	0xd0, 0x71, 0x7c, 0x2f, 0x70, 0xce, 0x03, 0x46, 0xec, 0x19, 0x45, 0x75, 0xfc, 0x08, 0x8e, 0x7c,
	0xdb, 0x9c, 0x5f, 0x58, 0x54, 0x7e, 0x84, 0x4e, 0x51, 0x03, 0x77, 0xa0, 0x69, 0xda, 0x1e, 0x65,
	0x36, 0xb1, 0x50, 0x13, 0xb7, 0xa1, 0x41, 0x26, 0x0e, 0x93, 0x50, 0x4b, 0x1e, 0x7c, 0xfb, 0x85,
	0xed, 0x7c, 0x6b, 0x23, 0x18, 0x7d, 0x06, 0xcd, 0xa2, 0x4c, 0xd2, 0xbf, 0xeb, 0x4f, 0xe6, 0xa6,
	0x27, 0x79, 0x25, 0xc9, 0x63, 0xbe, 0x6d, 0x9b, 0xf6, 0x0c, 0x69, 0x52, 0xcf, 0x70, 0xe4, 0x17,
	0x3c, 0x8a, 0xca, 0xa3, 0x11, 0x54, 0xe5, 0xa6, 0xc3, 0x18, 0xba, 0x86, 0x45, 0x5c, 0xd7, 0x3c,
	0x37, 0x0d, 0xa2, 0xec, 0x95, 0x70, 0x17, 0x80, 0xd1, 0x19, 0xa3, 0xae, 0x2b, 0xcf, 0xda, 0x68,
	0x01, 0xf5, 0x6c, 0x80, 0xe5, 0x15, 0x15, 0x3b, 0xb0, 0xc8, 0x84, 0x5a, 0xa8, 0x24, 0x03, 0x17,
	0xcc, 0x99, 0x90, 0x89, 0x69, 0x99, 0xde, 0x2b, 0xa4, 0xc9, 0x8b, 0xcc, 0xa8, 0x4d, 0x19, 0xb1,
	0x02, 0xd7, 0x70, 0x18, 0x45, 0x65, 0x29, 0x37, 0xf7, 0x2d, 0xcf, 0xcc, 0x72, 0x2a, 0xb2, 0xaa,
	0x3b, 0xf9, 0xe0, 0x92, 0x58, 0x3e, 0x45, 0xd5, 0xd1, 0xef, 0x1a, 0xd4, 0xb3, 0x55, 0x25, 0x9d,
	0x12, 0xc3, 0xf0, 0x19, 0x31, 0x5e, 0x65, 0x6f, 0x22, 0xcb, 0x67, 0x66, 0x66, 0x30, 0x40, 0x9d,
	0x51, 0x83, 0x58, 0x16, 0x2a, 0x4b, 0xe2, 0xf9, 0x27, 0xc1, 0xdc, 0x34, 0x98, 0x83, 0xaa, 0xc5,
	0x89, 0xc8, 0x53, 0x4d, 0xdd, 0xdd, 0x31, 0x02, 0xe2, 0x1b, 0xa8, 0x2e, 0x21, 0xcb, 0x99, 0x05,
	0x96, 0xe3, 0xba, 0xa8, 0x21, 0x0d, 0xcc, 0x29, 0xb1, 0x03, 0xf7, 0x1b, 0x9f, 0x30, 0x3a, 0x0d,
	0x28, 0x63, 0xa8, 0x89, 0x9f, 0xc2, 0x13, 0xe6, 0x38, 0x5e, 0x70, 0x0f, 0x6a, 0xe1, 0x27, 0xf0,
	0x48, 0x45, 0xc9, 0xc4, 0x75, 0x2c, 0xdf, 0xa3, 0x2a, 0x0c, 0x78, 0x00, 0xfd, 0x39, 0x9d, 0x9a,
	0x39, 0xe0, 0x6e, 0x91, 0xb6, 0xec, 0x27, 0x36, 0x46, 0x9d, 0xf1, 0x2f, 0xe5, 0xbd, 0xb5, 0x1a,
	0xdf, 0xac, 0x37, 0x82, 0xe3, 0x4b, 0xe8, 0x65, 0x3b, 0x60, 0xbb, 0xc6, 0xf1, 0xc9, 0x43, 0x6b,
	0x22, 0xdf, 0x01, 0xcf, 0xde, 0x7b, 0x98, 0x20, 0x5b, 0x5a, 0x2f, 0x3d, 0xd7, 0xf0, 0x4b, 0xe8,
	0xe5, 0x73, 0x59, 0x50, 0xf0, 0xe9, 0xfd, 0xb4, 0xc3, 0xe5, 0xf2, 0xec, 0xe4, 0x2f, 0x18, 0x5b,
	0xe5, 0xaf, 0xa0, 0xe3, 0x8a, 0x30, 0x11, 0xf9, 0xb6, 0xc1, 0xf7, 0x17, 0x50, 0x21, 0xf7, 0x8e,
	0x99, 0xd7, 0x4b, 0xf8, 0x0b, 0x00, 0xba, 0x5a, 0x3e, 0x9c, 0x9d, 0xaf, 0xaf, 0x77, 0x67, 0x7f,
	0x57, 0x57, 0x7f, 0x4c, 0x9f, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff, 0xae, 0x9f, 0x09, 0xe1, 0x4b,
	0x09, 0x00, 0x00,
}
