<template>
  <b-modal id="settings" title="Model Creation Settings" @ok="handleOk">
    <b-form-group
      id="model-limit"
      label="Maximum Generated Models:"
      label-for="num-models-spinner"
      description="Limits the number of models generated by the search process."
    >
      <b-form-spinbutton
        id="model-limit-spinner"
        v-model="modelLimit"
        inline
        min="1"
        max="100"
      />
    </b-form-group>
    <b-form-group
      id="time-limit"
      label="Time Limit:"
      label-for="time-limit-spinner"
      description="Sets that maximum allowed model search time in minutes."
    >
      <b-form-spinbutton
        id="time-limit-spinner"
        v-model="timeLimit"
        inline
        min="1"
        max="240"
      />
    </b-form-group>
    <b-form-group
      label="Model Training:"
      label-for="model-training-ratios"
      description="Selects faster model training or higher quality models."
    >
      <b-form-radio
        v-model="speedQuality"
        name="model-training-radios"
        value="speed"
      >
        Faster
      </b-form-radio>
      <b-form-radio
        v-model="speedQuality"
        name="model-training-radios"
        value="quality"
      >
        Higher Quality
      </b-form-radio>
    </b-form-group>
    <b-form-group
      label="Model Scoring:"
      label-for="model-scoring"
      description="Selects model accuracy scoring method."
    >
      <b-form-select v-model="selectedMetric" name="model-scoring" size="sm">
        <b-form-select-option
          v-for="metric in metrics"
          :key="metric.value.id"
          :value="metric.value.id"
        >
          {{ metric.text }}
        </b-form-select-option>
      </b-form-select>
      <p>
        <small>
          {{ description }}
        </small>
      </p>
    </b-form-group>
  </b-modal>
</template>

<script lang="ts">
import Vue from "vue";
import { ModelQuality } from "../store/requests";
import {
  getters as datasetGetters,
  actions as datasetActions,
} from "../store/dataset/module";
import { overlayRouteEntry } from "../util/routes";
import { MetricDropdownItem, TaskTypes } from "../store/dataset";
import { getters as routeGetters } from "../store/route/module";

// Dialog for setting model creation preferences.  The results are saved to the route to ensure
// that users don't have to set them for each run.
export default Vue.extend({
  name: "settings-modal",

  data() {
    return {
      modelLimit: routeGetters.getModelLimit(this.$store) || 5,
      timeLimit: routeGetters.getModelTimeLimit(this.$store) || 5,
      speedQuality:
        routeGetters.getModelQuality(this.$store) ||
        ModelQuality.HIGHER_QUALITY,
      // fill this from the API later, first posting back the target's type
      // then getting a list of allowed scoring methods with keys, description
      selectedMetric: null,
    };
  },

  computed: {
    description(): string {
      return this.metrics.filter((m) => m.value.id === this.selectedMetric)[0]
        ?.value?.description;
    },
    metrics(): MetricDropdownItem[] {
      const baseMetrics = datasetGetters.getModelingMetrics(this.$store);
      return baseMetrics.map((m) => {
        return {
          value: {
            id: m.id,
            description: m.description,
          },
          text: m.displayName,
        };
      });
    },
  },

  async beforeMount() {
    const task = routeGetters.getRouteTask(this.$store);
    if (!task) return;
    await datasetActions.fetchModelingMetrics(this.$store, {
      task: task,
    });
    if (task.includes(TaskTypes.CLASSIFICATION)) {
      if (task.includes(TaskTypes.MULTICLASS)) {
        this.selectedMetric = "f1Macro";
      } else {
        this.selectedMetric = "f1";
      }
    } else if (task.includes(TaskTypes.REGRESSION)) {
      this.selectedMetric = "meanAbsoluteError";
    } else {
      this.selectedMetric = null;
    }
  },

  methods: {
    handleOk() {
      const entry = overlayRouteEntry(routeGetters.getRoute(this.$store), {
        modelLimit: this.modelLimit,
        modelTimeLimit: this.timeLimit,
        modelQuality: this.speedQuality,
        metrics: this.selectedMetric,
      });
      this.$router.push(entry).catch((err) => console.warn(err));
    },
  },
});
</script>

<style></style>
