FROM registry.datadrivendiscovery.org/uncharted_qntfy/ta3ta2_integration/qntfy_main:beta

RUN pip3 install -U --no-deps git+https://gitlab.com/datadrivendiscovery/common-primitives@filter-primitives#egg=common_primitives -t /src/common-primitives
