export enum Feature {
	SEARCH_DATASETS = 'SEARCH_DATASETS',
	SELECT_DATASET = 'SELECT_DATASET',
	SELECT_TARGET = 'SELECT_TARGET',
	RETYPE_FEATURE = 'RETYPE_FEATURE',
	RANK_FEATURES = 'RANK_FEATURES',
	GEOCODE_FEATURES = 'GEOCODE_FEATURES',
	JOIN_DATASETS = 'JOIN_DATASETS',
	ADD_FEATURE = 'ADD_FEATURE',
	ADD_ALL_FEATURES = 'ADD_ALL_FEATURES',
	REMOVE_FEATURE = 'REMOVE_FEATURE',
	REMOVE_ALL_FEATURES = 'REMOVE_ALL_FEATURES',
	CHANGE_HIGHLIGHT = 'CHANGE_HIGHLIGHT',
	CHANGE_SELECTION = 'CHANGE_SELECTION',
	FILTER_DATA = 'FILTER_DATA',
	SEARCH_FEATURES = 'SEARCH_FEATURES',
	CREATE_MODEL = 'CREATE_MODEL',
	SELECT_MODEL = 'SELECT_MODEL',
	EXPORT_MODEL = 'EXPORT_MODEL',
}

export enum Activity {
	DATA_PREPARATION = 'DATA_PREPARATION',
	PROBLEM_DEFINITIION = 'PROBLEM_DEFINITION',
	MODEL_SELECTION = 'MODEL_SELECTION'
}
