// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/pipeline/core.proto

/*
Package pipeline is a generated protocol buffer package.

It is generated from these files:
	api/pipeline/core.proto

It has these top-level messages:
	SessionContext
	Status
	Response
	SessionRequest
	SessionResponse
	Feature
	PipelineCreateRequest
	Score
	Pipeline
	PipelineCreateResult
	PipelineExecuteRequest
	PipelineExecuteResult
	PipelineListRequest
	PipelineDeleteRequest
	PipelineListResult
	PipelineCreateResultsRequest
	PipelineExecuteResultsRequest
	PipelineExportRequest
	UpdateProblemSchemaRequest
*/
package pipeline

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_UNKNOWN             StatusCode = 0
	StatusCode_OK                  StatusCode = 1
	StatusCode_CANCELLED           StatusCode = 2
	StatusCode_SESSION_UNKNOWN     StatusCode = 3
	StatusCode_SESSION_ENDED       StatusCode = 4
	StatusCode_SESSION_EXPIRED     StatusCode = 5
	StatusCode_INVALID_ARGUMENT    StatusCode = 6
	StatusCode_RESOURCE_EXHAUSTED  StatusCode = 7
	StatusCode_UNAVAILABLE         StatusCode = 8
	StatusCode_FAILED_PRECONDITION StatusCode = 9
	StatusCode_OUT_OF_RANGE        StatusCode = 10
	StatusCode_UNIMPLEMENTED       StatusCode = 11
	StatusCode_INTERNAL            StatusCode = 12
	StatusCode_ABORTED             StatusCode = 13
)

var StatusCode_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "OK",
	2:  "CANCELLED",
	3:  "SESSION_UNKNOWN",
	4:  "SESSION_ENDED",
	5:  "SESSION_EXPIRED",
	6:  "INVALID_ARGUMENT",
	7:  "RESOURCE_EXHAUSTED",
	8:  "UNAVAILABLE",
	9:  "FAILED_PRECONDITION",
	10: "OUT_OF_RANGE",
	11: "UNIMPLEMENTED",
	12: "INTERNAL",
	13: "ABORTED",
}
var StatusCode_value = map[string]int32{
	"UNKNOWN":             0,
	"OK":                  1,
	"CANCELLED":           2,
	"SESSION_UNKNOWN":     3,
	"SESSION_ENDED":       4,
	"SESSION_EXPIRED":     5,
	"INVALID_ARGUMENT":    6,
	"RESOURCE_EXHAUSTED":  7,
	"UNAVAILABLE":         8,
	"FAILED_PRECONDITION": 9,
	"OUT_OF_RANGE":        10,
	"UNIMPLEMENTED":       11,
	"INTERNAL":            12,
	"ABORTED":             13,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}
func (StatusCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Progress int32

const (
	Progress_SUBMITTED Progress = 0
	Progress_RUNNING   Progress = 1
	Progress_UPDATED   Progress = 2
	Progress_COMPLETED Progress = 3
)

var Progress_name = map[int32]string{
	0: "SUBMITTED",
	1: "RUNNING",
	2: "UPDATED",
	3: "COMPLETED",
}
var Progress_value = map[string]int32{
	"SUBMITTED": 0,
	"RUNNING":   1,
	"UPDATED":   2,
	"COMPLETED": 3,
}

func (x Progress) String() string {
	return proto.EnumName(Progress_name, int32(x))
}
func (Progress) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type TaskType int32

const (
	TaskType_TASK_TYPE_UNDEFINED     TaskType = 0
	TaskType_CLASSIFICATION          TaskType = 1
	TaskType_REGRESSION              TaskType = 2
	TaskType_SIMILARITY_MATCHING     TaskType = 3
	TaskType_LINK_PREDICTION         TaskType = 4
	TaskType_VERTEX_NOMINATION       TaskType = 5
	TaskType_COMMUNITY_DETECTION     TaskType = 6
	TaskType_GRAPH_MATCHING          TaskType = 7
	TaskType_TIMESERIES_FORECASTING  TaskType = 8
	TaskType_COLLABORATIVE_FILTERING TaskType = 9
)

var TaskType_name = map[int32]string{
	0: "TASK_TYPE_UNDEFINED",
	1: "CLASSIFICATION",
	2: "REGRESSION",
	3: "SIMILARITY_MATCHING",
	4: "LINK_PREDICTION",
	5: "VERTEX_NOMINATION",
	6: "COMMUNITY_DETECTION",
	7: "GRAPH_MATCHING",
	8: "TIMESERIES_FORECASTING",
	9: "COLLABORATIVE_FILTERING",
}
var TaskType_value = map[string]int32{
	"TASK_TYPE_UNDEFINED":     0,
	"CLASSIFICATION":          1,
	"REGRESSION":              2,
	"SIMILARITY_MATCHING":     3,
	"LINK_PREDICTION":         4,
	"VERTEX_NOMINATION":       5,
	"COMMUNITY_DETECTION":     6,
	"GRAPH_MATCHING":          7,
	"TIMESERIES_FORECASTING":  8,
	"COLLABORATIVE_FILTERING": 9,
}

func (x TaskType) String() string {
	return proto.EnumName(TaskType_name, int32(x))
}
func (TaskType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type TaskSubtype int32

const (
	TaskSubtype_TASK_SUBTYPE_UNDEFINED TaskSubtype = 0
	TaskSubtype_NONE                   TaskSubtype = 1
	TaskSubtype_BINARY                 TaskSubtype = 2
	TaskSubtype_MULTICLASS             TaskSubtype = 3
	TaskSubtype_MULTILABEL             TaskSubtype = 4
	TaskSubtype_UNIVARIATE             TaskSubtype = 5
	TaskSubtype_MULTIVARIATE           TaskSubtype = 6
	TaskSubtype_OVERLAPPING            TaskSubtype = 7
	TaskSubtype_NONOVERLAPPING         TaskSubtype = 8
)

var TaskSubtype_name = map[int32]string{
	0: "TASK_SUBTYPE_UNDEFINED",
	1: "NONE",
	2: "BINARY",
	3: "MULTICLASS",
	4: "MULTILABEL",
	5: "UNIVARIATE",
	6: "MULTIVARIATE",
	7: "OVERLAPPING",
	8: "NONOVERLAPPING",
}
var TaskSubtype_value = map[string]int32{
	"TASK_SUBTYPE_UNDEFINED": 0,
	"NONE":           1,
	"BINARY":         2,
	"MULTICLASS":     3,
	"MULTILABEL":     4,
	"UNIVARIATE":     5,
	"MULTIVARIATE":   6,
	"OVERLAPPING":    7,
	"NONOVERLAPPING": 8,
}

func (x TaskSubtype) String() string {
	return proto.EnumName(TaskSubtype_name, int32(x))
}
func (TaskSubtype) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type OutputType int32

const (
	OutputType_OUTPUT_TYPE_UNDEFINED OutputType = 0
	OutputType_CLASS_LABEL           OutputType = 1
	OutputType_PROBABILITY           OutputType = 2
	OutputType_REAL                  OutputType = 3
	OutputType_NODE_ID               OutputType = 4
	OutputType_VECTOR_CLASS_LABEL    OutputType = 5
	OutputType_VECTOR_STOCHASTIC     OutputType = 6
	OutputType_VECTOR_REAL           OutputType = 7
	OutputType_FILE                  OutputType = 8
)

var OutputType_name = map[int32]string{
	0: "OUTPUT_TYPE_UNDEFINED",
	1: "CLASS_LABEL",
	2: "PROBABILITY",
	3: "REAL",
	4: "NODE_ID",
	5: "VECTOR_CLASS_LABEL",
	6: "VECTOR_STOCHASTIC",
	7: "VECTOR_REAL",
	8: "FILE",
}
var OutputType_value = map[string]int32{
	"OUTPUT_TYPE_UNDEFINED": 0,
	"CLASS_LABEL":           1,
	"PROBABILITY":           2,
	"REAL":                  3,
	"NODE_ID":               4,
	"VECTOR_CLASS_LABEL":    5,
	"VECTOR_STOCHASTIC":     6,
	"VECTOR_REAL":           7,
	"FILE":                  8,
}

func (x OutputType) String() string {
	return proto.EnumName(OutputType_name, int32(x))
}
func (OutputType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Metric int32

const (
	Metric_METRIC_UNDEFINED              Metric = 0
	Metric_ACCURACY                      Metric = 1
	Metric_F1                            Metric = 2
	Metric_F1_MICRO                      Metric = 3
	Metric_F1_MACRO                      Metric = 4
	Metric_ROC_AUC                       Metric = 5
	Metric_ROC_AUC_MICRO                 Metric = 6
	Metric_ROC_AUC_MACRO                 Metric = 7
	Metric_ROOT_MEAN_SQUARED_ERROR       Metric = 8
	Metric_ROOT_MEAN_SQUARED_ERROR_AVG   Metric = 9
	Metric_MEAN_ABSOLUTE_ERROR           Metric = 10
	Metric_R_SQUARED                     Metric = 11
	Metric_NORMALIZED_MUTUAL_INFORMATION Metric = 12
	Metric_JACCARD_SIMILARITY_SCORE      Metric = 13
	Metric_EXECUTION_TIME                Metric = 14
)

var Metric_name = map[int32]string{
	0:  "METRIC_UNDEFINED",
	1:  "ACCURACY",
	2:  "F1",
	3:  "F1_MICRO",
	4:  "F1_MACRO",
	5:  "ROC_AUC",
	6:  "ROC_AUC_MICRO",
	7:  "ROC_AUC_MACRO",
	8:  "ROOT_MEAN_SQUARED_ERROR",
	9:  "ROOT_MEAN_SQUARED_ERROR_AVG",
	10: "MEAN_ABSOLUTE_ERROR",
	11: "R_SQUARED",
	12: "NORMALIZED_MUTUAL_INFORMATION",
	13: "JACCARD_SIMILARITY_SCORE",
	14: "EXECUTION_TIME",
}
var Metric_value = map[string]int32{
	"METRIC_UNDEFINED":              0,
	"ACCURACY":                      1,
	"F1":                            2,
	"F1_MICRO":                      3,
	"F1_MACRO":                      4,
	"ROC_AUC":                       5,
	"ROC_AUC_MICRO":                 6,
	"ROC_AUC_MACRO":                 7,
	"ROOT_MEAN_SQUARED_ERROR":       8,
	"ROOT_MEAN_SQUARED_ERROR_AVG":   9,
	"MEAN_ABSOLUTE_ERROR":           10,
	"R_SQUARED":                     11,
	"NORMALIZED_MUTUAL_INFORMATION": 12,
	"JACCARD_SIMILARITY_SCORE":      13,
	"EXECUTION_TIME":                14,
}

func (x Metric) String() string {
	return proto.EnumName(Metric_name, int32(x))
}
func (Metric) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SessionContext struct {
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
}

func (m *SessionContext) Reset()                    { *m = SessionContext{} }
func (m *SessionContext) String() string            { return proto.CompactTextString(m) }
func (*SessionContext) ProtoMessage()               {}
func (*SessionContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SessionContext) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type Status struct {
	Code    StatusCode `protobuf:"varint,1,opt,name=code,enum=StatusCode" json:"code,omitempty"`
	Details string     `protobuf:"bytes,2,opt,name=details" json:"details,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Status) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_UNKNOWN
}

func (m *Status) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

type Response struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// in the future we could also pass arguments allowing one to fork an existing session,
// or provide resource limits on a session (asking TA2 system to terminate work if it exceeds a given limit)
type SessionRequest struct {
	UserAgent string `protobuf:"bytes,1,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *SessionRequest) Reset()                    { *m = SessionRequest{} }
func (m *SessionRequest) String() string            { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()               {}
func (*SessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SessionRequest) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *SessionRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SessionResponse struct {
	ResponseInfo *Response       `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	UserAgent    string          `protobuf:"bytes,2,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	Version      string          `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	Context      *SessionContext `protobuf:"bytes,4,opt,name=context" json:"context,omitempty"`
}

func (m *SessionResponse) Reset()                    { *m = SessionResponse{} }
func (m *SessionResponse) String() string            { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()               {}
func (*SessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SessionResponse) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *SessionResponse) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *SessionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *SessionResponse) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type Feature struct {
	FeatureId string `protobuf:"bytes,1,opt,name=feature_id,json=featureId" json:"feature_id,omitempty"`
	DataUri   string `protobuf:"bytes,2,opt,name=data_uri,json=dataUri" json:"data_uri,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Feature) GetFeatureId() string {
	if m != nil {
		return m.FeatureId
	}
	return ""
}

func (m *Feature) GetDataUri() string {
	if m != nil {
		return m.DataUri
	}
	return ""
}

type PipelineCreateRequest struct {
	Context         *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	TrainFeatures   []*Feature      `protobuf:"bytes,2,rep,name=train_features,json=trainFeatures" json:"train_features,omitempty"`
	Task            TaskType        `protobuf:"varint,3,opt,name=task,enum=TaskType" json:"task,omitempty"`
	TaskSubtype     TaskSubtype     `protobuf:"varint,4,opt,name=task_subtype,json=taskSubtype,enum=TaskSubtype" json:"task_subtype,omitempty"`
	TaskDescription string          `protobuf:"bytes,5,opt,name=task_description,json=taskDescription" json:"task_description,omitempty"`
	Output          OutputType      `protobuf:"varint,6,opt,name=output,enum=OutputType" json:"output,omitempty"`
	Metrics         []Metric        `protobuf:"varint,7,rep,packed,name=metrics,enum=Metric" json:"metrics,omitempty"`
	TargetFeatures  []*Feature      `protobuf:"bytes,8,rep,name=target_features,json=targetFeatures" json:"target_features,omitempty"`
	MaxPipelines    int32           `protobuf:"varint,9,opt,name=max_pipelines,json=maxPipelines" json:"max_pipelines,omitempty"`
}

func (m *PipelineCreateRequest) Reset()                    { *m = PipelineCreateRequest{} }
func (m *PipelineCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineCreateRequest) ProtoMessage()               {}
func (*PipelineCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PipelineCreateRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineCreateRequest) GetTrainFeatures() []*Feature {
	if m != nil {
		return m.TrainFeatures
	}
	return nil
}

func (m *PipelineCreateRequest) GetTask() TaskType {
	if m != nil {
		return m.Task
	}
	return TaskType_TASK_TYPE_UNDEFINED
}

func (m *PipelineCreateRequest) GetTaskSubtype() TaskSubtype {
	if m != nil {
		return m.TaskSubtype
	}
	return TaskSubtype_TASK_SUBTYPE_UNDEFINED
}

func (m *PipelineCreateRequest) GetTaskDescription() string {
	if m != nil {
		return m.TaskDescription
	}
	return ""
}

func (m *PipelineCreateRequest) GetOutput() OutputType {
	if m != nil {
		return m.Output
	}
	return OutputType_OUTPUT_TYPE_UNDEFINED
}

func (m *PipelineCreateRequest) GetMetrics() []Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *PipelineCreateRequest) GetTargetFeatures() []*Feature {
	if m != nil {
		return m.TargetFeatures
	}
	return nil
}

func (m *PipelineCreateRequest) GetMaxPipelines() int32 {
	if m != nil {
		return m.MaxPipelines
	}
	return 0
}

type Score struct {
	Metric Metric  `protobuf:"varint,1,opt,name=metric,enum=Metric" json:"metric,omitempty"`
	Value  float32 `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
}

func (m *Score) Reset()                    { *m = Score{} }
func (m *Score) String() string            { return proto.CompactTextString(m) }
func (*Score) ProtoMessage()               {}
func (*Score) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Score) GetMetric() Metric {
	if m != nil {
		return m.Metric
	}
	return Metric_METRIC_UNDEFINED
}

func (m *Score) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Pipeline struct {
	PredictResultUris []string   `protobuf:"bytes,1,rep,name=predict_result_uris,json=predictResultUris" json:"predict_result_uris,omitempty"`
	Output            OutputType `protobuf:"varint,2,opt,name=output,enum=OutputType" json:"output,omitempty"`
	Scores            []*Score   `protobuf:"bytes,3,rep,name=scores" json:"scores,omitempty"`
}

func (m *Pipeline) Reset()                    { *m = Pipeline{} }
func (m *Pipeline) String() string            { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()               {}
func (*Pipeline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Pipeline) GetPredictResultUris() []string {
	if m != nil {
		return m.PredictResultUris
	}
	return nil
}

func (m *Pipeline) GetOutput() OutputType {
	if m != nil {
		return m.Output
	}
	return OutputType_OUTPUT_TYPE_UNDEFINED
}

func (m *Pipeline) GetScores() []*Score {
	if m != nil {
		return m.Scores
	}
	return nil
}

type PipelineCreateResult struct {
	ResponseInfo *Response `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	ProgressInfo Progress  `protobuf:"varint,2,opt,name=progress_info,json=progressInfo,enum=Progress" json:"progress_info,omitempty"`
	PipelineId   string    `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	// Will be set if progress info value is UPDATED or COMPLETED
	PipelineInfo *Pipeline `protobuf:"bytes,4,opt,name=pipeline_info,json=pipelineInfo" json:"pipeline_info,omitempty"`
}

func (m *PipelineCreateResult) Reset()                    { *m = PipelineCreateResult{} }
func (m *PipelineCreateResult) String() string            { return proto.CompactTextString(m) }
func (*PipelineCreateResult) ProtoMessage()               {}
func (*PipelineCreateResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PipelineCreateResult) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *PipelineCreateResult) GetProgressInfo() Progress {
	if m != nil {
		return m.ProgressInfo
	}
	return Progress_SUBMITTED
}

func (m *PipelineCreateResult) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineCreateResult) GetPipelineInfo() *Pipeline {
	if m != nil {
		return m.PipelineInfo
	}
	return nil
}

type PipelineExecuteRequest struct {
	Context         *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	PipelineId      string          `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	PredictFeatures []*Feature      `protobuf:"bytes,3,rep,name=predict_features,json=predictFeatures" json:"predict_features,omitempty"`
}

func (m *PipelineExecuteRequest) Reset()                    { *m = PipelineExecuteRequest{} }
func (m *PipelineExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineExecuteRequest) ProtoMessage()               {}
func (*PipelineExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PipelineExecuteRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineExecuteRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineExecuteRequest) GetPredictFeatures() []*Feature {
	if m != nil {
		return m.PredictFeatures
	}
	return nil
}

type PipelineExecuteResult struct {
	ResponseInfo *Response `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	ProgressInfo Progress  `protobuf:"varint,2,opt,name=progress_info,json=progressInfo,enum=Progress" json:"progress_info,omitempty"`
	PipelineId   string    `protobuf:"bytes,3,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	// Will be set if progress info value is UPDATED or COMPLETED
	ResultUris []string `protobuf:"bytes,4,rep,name=result_uris,json=resultUris" json:"result_uris,omitempty"`
}

func (m *PipelineExecuteResult) Reset()                    { *m = PipelineExecuteResult{} }
func (m *PipelineExecuteResult) String() string            { return proto.CompactTextString(m) }
func (*PipelineExecuteResult) ProtoMessage()               {}
func (*PipelineExecuteResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PipelineExecuteResult) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *PipelineExecuteResult) GetProgressInfo() Progress {
	if m != nil {
		return m.ProgressInfo
	}
	return Progress_SUBMITTED
}

func (m *PipelineExecuteResult) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineExecuteResult) GetResultUris() []string {
	if m != nil {
		return m.ResultUris
	}
	return nil
}

type PipelineListRequest struct {
	Context *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
}

func (m *PipelineListRequest) Reset()                    { *m = PipelineListRequest{} }
func (m *PipelineListRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineListRequest) ProtoMessage()               {}
func (*PipelineListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *PipelineListRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

type PipelineDeleteRequest struct {
	Context           *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	DeletePipelineIds []string        `protobuf:"bytes,2,rep,name=delete_pipeline_ids,json=deletePipelineIds" json:"delete_pipeline_ids,omitempty"`
}

func (m *PipelineDeleteRequest) Reset()                    { *m = PipelineDeleteRequest{} }
func (m *PipelineDeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineDeleteRequest) ProtoMessage()               {}
func (*PipelineDeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *PipelineDeleteRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineDeleteRequest) GetDeletePipelineIds() []string {
	if m != nil {
		return m.DeletePipelineIds
	}
	return nil
}

type PipelineListResult struct {
	ResponseInfo *Response `protobuf:"bytes,1,opt,name=response_info,json=responseInfo" json:"response_info,omitempty"`
	PipelineIds  []string  `protobuf:"bytes,2,rep,name=pipeline_ids,json=pipelineIds" json:"pipeline_ids,omitempty"`
}

func (m *PipelineListResult) Reset()                    { *m = PipelineListResult{} }
func (m *PipelineListResult) String() string            { return proto.CompactTextString(m) }
func (*PipelineListResult) ProtoMessage()               {}
func (*PipelineListResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *PipelineListResult) GetResponseInfo() *Response {
	if m != nil {
		return m.ResponseInfo
	}
	return nil
}

func (m *PipelineListResult) GetPipelineIds() []string {
	if m != nil {
		return m.PipelineIds
	}
	return nil
}

type PipelineCreateResultsRequest struct {
	Context     *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	PipelineIds []string        `protobuf:"bytes,2,rep,name=pipeline_ids,json=pipelineIds" json:"pipeline_ids,omitempty"`
}

func (m *PipelineCreateResultsRequest) Reset()                    { *m = PipelineCreateResultsRequest{} }
func (m *PipelineCreateResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineCreateResultsRequest) ProtoMessage()               {}
func (*PipelineCreateResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PipelineCreateResultsRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineCreateResultsRequest) GetPipelineIds() []string {
	if m != nil {
		return m.PipelineIds
	}
	return nil
}

type PipelineExecuteResultsRequest struct {
	Context     *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	PipelineIds []string        `protobuf:"bytes,2,rep,name=pipeline_ids,json=pipelineIds" json:"pipeline_ids,omitempty"`
}

func (m *PipelineExecuteResultsRequest) Reset()                    { *m = PipelineExecuteResultsRequest{} }
func (m *PipelineExecuteResultsRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineExecuteResultsRequest) ProtoMessage()               {}
func (*PipelineExecuteResultsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *PipelineExecuteResultsRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineExecuteResultsRequest) GetPipelineIds() []string {
	if m != nil {
		return m.PipelineIds
	}
	return nil
}

type PipelineExportRequest struct {
	Context         *SessionContext `protobuf:"bytes,1,opt,name=context" json:"context,omitempty"`
	PipelineId      string          `protobuf:"bytes,2,opt,name=pipeline_id,json=pipelineId" json:"pipeline_id,omitempty"`
	PipelineExecUri string          `protobuf:"bytes,3,opt,name=pipeline_exec_uri,json=pipelineExecUri" json:"pipeline_exec_uri,omitempty"`
}

func (m *PipelineExportRequest) Reset()                    { *m = PipelineExportRequest{} }
func (m *PipelineExportRequest) String() string            { return proto.CompactTextString(m) }
func (*PipelineExportRequest) ProtoMessage()               {}
func (*PipelineExportRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PipelineExportRequest) GetContext() *SessionContext {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PipelineExportRequest) GetPipelineId() string {
	if m != nil {
		return m.PipelineId
	}
	return ""
}

func (m *PipelineExportRequest) GetPipelineExecUri() string {
	if m != nil {
		return m.PipelineExecUri
	}
	return ""
}

type UpdateProblemSchemaRequest struct {
	Updates []*UpdateProblemSchemaRequest_ReplaceProblemSchemaField `protobuf:"bytes,1,rep,name=updates" json:"updates,omitempty"`
}

func (m *UpdateProblemSchemaRequest) Reset()                    { *m = UpdateProblemSchemaRequest{} }
func (m *UpdateProblemSchemaRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProblemSchemaRequest) ProtoMessage()               {}
func (*UpdateProblemSchemaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UpdateProblemSchemaRequest) GetUpdates() []*UpdateProblemSchemaRequest_ReplaceProblemSchemaField {
	if m != nil {
		return m.Updates
	}
	return nil
}

type UpdateProblemSchemaRequest_ReplaceProblemSchemaField struct {
	// Types that are valid to be assigned to Update:
	//	*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskType
	//	*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskSubtype
	//	*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskDescription
	//	*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OutputType
	//	*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_Metric
	Update isUpdateProblemSchemaRequest_ReplaceProblemSchemaField_Update `protobuf_oneof:"update"`
}

func (m *UpdateProblemSchemaRequest_ReplaceProblemSchemaField) Reset() {
	*m = UpdateProblemSchemaRequest_ReplaceProblemSchemaField{}
}
func (m *UpdateProblemSchemaRequest_ReplaceProblemSchemaField) String() string {
	return proto.CompactTextString(m)
}
func (*UpdateProblemSchemaRequest_ReplaceProblemSchemaField) ProtoMessage() {}
func (*UpdateProblemSchemaRequest_ReplaceProblemSchemaField) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{18, 0}
}

type isUpdateProblemSchemaRequest_ReplaceProblemSchemaField_Update interface {
	isUpdateProblemSchemaRequest_ReplaceProblemSchemaField_Update()
}

type UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskType struct {
	TaskType TaskType `protobuf:"varint,1,opt,name=task_type,json=taskType,enum=TaskType,oneof"`
}
type UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskSubtype struct {
	TaskSubtype TaskSubtype `protobuf:"varint,2,opt,name=task_subtype,json=taskSubtype,enum=TaskSubtype,oneof"`
}
type UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskDescription struct {
	TaskDescription string `protobuf:"bytes,3,opt,name=task_description,json=taskDescription,oneof"`
}
type UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OutputType struct {
	OutputType OutputType `protobuf:"varint,4,opt,name=output_type,json=outputType,enum=OutputType,oneof"`
}
type UpdateProblemSchemaRequest_ReplaceProblemSchemaField_Metric struct {
	Metric Metric `protobuf:"varint,5,opt,name=metric,enum=Metric,oneof"`
}

func (*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskType) isUpdateProblemSchemaRequest_ReplaceProblemSchemaField_Update() {
}
func (*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskSubtype) isUpdateProblemSchemaRequest_ReplaceProblemSchemaField_Update() {
}
func (*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskDescription) isUpdateProblemSchemaRequest_ReplaceProblemSchemaField_Update() {
}
func (*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OutputType) isUpdateProblemSchemaRequest_ReplaceProblemSchemaField_Update() {
}
func (*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_Metric) isUpdateProblemSchemaRequest_ReplaceProblemSchemaField_Update() {
}

func (m *UpdateProblemSchemaRequest_ReplaceProblemSchemaField) GetUpdate() isUpdateProblemSchemaRequest_ReplaceProblemSchemaField_Update {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *UpdateProblemSchemaRequest_ReplaceProblemSchemaField) GetTaskType() TaskType {
	if x, ok := m.GetUpdate().(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskType); ok {
		return x.TaskType
	}
	return TaskType_TASK_TYPE_UNDEFINED
}

func (m *UpdateProblemSchemaRequest_ReplaceProblemSchemaField) GetTaskSubtype() TaskSubtype {
	if x, ok := m.GetUpdate().(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskSubtype); ok {
		return x.TaskSubtype
	}
	return TaskSubtype_TASK_SUBTYPE_UNDEFINED
}

func (m *UpdateProblemSchemaRequest_ReplaceProblemSchemaField) GetTaskDescription() string {
	if x, ok := m.GetUpdate().(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskDescription); ok {
		return x.TaskDescription
	}
	return ""
}

func (m *UpdateProblemSchemaRequest_ReplaceProblemSchemaField) GetOutputType() OutputType {
	if x, ok := m.GetUpdate().(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OutputType); ok {
		return x.OutputType
	}
	return OutputType_OUTPUT_TYPE_UNDEFINED
}

func (m *UpdateProblemSchemaRequest_ReplaceProblemSchemaField) GetMetric() Metric {
	if x, ok := m.GetUpdate().(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_Metric); ok {
		return x.Metric
	}
	return Metric_METRIC_UNDEFINED
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*UpdateProblemSchemaRequest_ReplaceProblemSchemaField) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OneofMarshaler, _UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OneofUnmarshaler, _UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OneofSizer, []interface{}{
		(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskType)(nil),
		(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskSubtype)(nil),
		(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskDescription)(nil),
		(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OutputType)(nil),
		(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField_Metric)(nil),
	}
}

func _UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField)
	// update
	switch x := m.Update.(type) {
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskType:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.TaskType))
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskSubtype:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.TaskSubtype))
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskDescription:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.TaskDescription)
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OutputType:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.OutputType))
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_Metric:
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Metric))
	case nil:
	default:
		return fmt.Errorf("UpdateProblemSchemaRequest_ReplaceProblemSchemaField.Update has unexpected type %T", x)
	}
	return nil
}

func _UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField)
	switch tag {
	case 1: // update.task_type
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Update = &UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskType{TaskType(x)}
		return true, err
	case 2: // update.task_subtype
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Update = &UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskSubtype{TaskSubtype(x)}
		return true, err
	case 3: // update.task_description
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Update = &UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskDescription{x}
		return true, err
	case 4: // update.output_type
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Update = &UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OutputType{OutputType(x)}
		return true, err
	case 5: // update.metric
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Update = &UpdateProblemSchemaRequest_ReplaceProblemSchemaField_Metric{Metric(x)}
		return true, err
	default:
		return false, nil
	}
}

func _UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*UpdateProblemSchemaRequest_ReplaceProblemSchemaField)
	// update
	switch x := m.Update.(type) {
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskType:
		n += proto.SizeVarint(1<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.TaskType))
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskSubtype:
		n += proto.SizeVarint(2<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.TaskSubtype))
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_TaskDescription:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.TaskDescription)))
		n += len(x.TaskDescription)
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_OutputType:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.OutputType))
	case *UpdateProblemSchemaRequest_ReplaceProblemSchemaField_Metric:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Metric))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

var E_ProtocolVersion = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         54100,
	Name:          "protocol_version",
	Tag:           "bytes,54100,opt,name=protocol_version,json=protocolVersion",
	Filename:      "api/pipeline/core.proto",
}

func init() {
	proto.RegisterType((*SessionContext)(nil), "SessionContext")
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*SessionRequest)(nil), "SessionRequest")
	proto.RegisterType((*SessionResponse)(nil), "SessionResponse")
	proto.RegisterType((*Feature)(nil), "Feature")
	proto.RegisterType((*PipelineCreateRequest)(nil), "PipelineCreateRequest")
	proto.RegisterType((*Score)(nil), "Score")
	proto.RegisterType((*Pipeline)(nil), "Pipeline")
	proto.RegisterType((*PipelineCreateResult)(nil), "PipelineCreateResult")
	proto.RegisterType((*PipelineExecuteRequest)(nil), "PipelineExecuteRequest")
	proto.RegisterType((*PipelineExecuteResult)(nil), "PipelineExecuteResult")
	proto.RegisterType((*PipelineListRequest)(nil), "PipelineListRequest")
	proto.RegisterType((*PipelineDeleteRequest)(nil), "PipelineDeleteRequest")
	proto.RegisterType((*PipelineListResult)(nil), "PipelineListResult")
	proto.RegisterType((*PipelineCreateResultsRequest)(nil), "PipelineCreateResultsRequest")
	proto.RegisterType((*PipelineExecuteResultsRequest)(nil), "PipelineExecuteResultsRequest")
	proto.RegisterType((*PipelineExportRequest)(nil), "PipelineExportRequest")
	proto.RegisterType((*UpdateProblemSchemaRequest)(nil), "UpdateProblemSchemaRequest")
	proto.RegisterType((*UpdateProblemSchemaRequest_ReplaceProblemSchemaField)(nil), "UpdateProblemSchemaRequest.ReplaceProblemSchemaField")
	proto.RegisterEnum("StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("Progress", Progress_name, Progress_value)
	proto.RegisterEnum("TaskType", TaskType_name, TaskType_value)
	proto.RegisterEnum("TaskSubtype", TaskSubtype_name, TaskSubtype_value)
	proto.RegisterEnum("OutputType", OutputType_name, OutputType_value)
	proto.RegisterEnum("Metric", Metric_name, Metric_value)
	proto.RegisterExtension(E_ProtocolVersion)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Core service

type CoreClient interface {
	// Train step - multiple result messages returned via GRPC streaming.
	CreatePipelines(ctx context.Context, in *PipelineCreateRequest, opts ...grpc.CallOption) (Core_CreatePipelinesClient, error)
	// Predict step - multiple results messages returned via GRPC streaming.
	ExecutePipeline(ctx context.Context, in *PipelineExecuteRequest, opts ...grpc.CallOption) (Core_ExecutePipelineClient, error)
	// Manage pipelines already present in the session.
	ListPipelines(ctx context.Context, in *PipelineListRequest, opts ...grpc.CallOption) (*PipelineListResult, error)
	DeletePipelines(ctx context.Context, in *PipelineDeleteRequest, opts ...grpc.CallOption) (*PipelineListResult, error)
	// Obtain results
	GetCreatePipelineResults(ctx context.Context, in *PipelineCreateResultsRequest, opts ...grpc.CallOption) (Core_GetCreatePipelineResultsClient, error)
	GetExecutePipelineResults(ctx context.Context, in *PipelineExecuteResultsRequest, opts ...grpc.CallOption) (Core_GetExecutePipelineResultsClient, error)
	// Export executable of a pipeline, including any optional preprocessing used in session
	ExportPipeline(ctx context.Context, in *PipelineExportRequest, opts ...grpc.CallOption) (*Response, error)
	// Update problem schema
	UpdateProblemSchema(ctx context.Context, in *UpdateProblemSchemaRequest, opts ...grpc.CallOption) (*Response, error)
	// Session management
	StartSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	EndSession(ctx context.Context, in *SessionContext, opts ...grpc.CallOption) (*Response, error)
}

type coreClient struct {
	cc *grpc.ClientConn
}

func NewCoreClient(cc *grpc.ClientConn) CoreClient {
	return &coreClient{cc}
}

func (c *coreClient) CreatePipelines(ctx context.Context, in *PipelineCreateRequest, opts ...grpc.CallOption) (Core_CreatePipelinesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Core_serviceDesc.Streams[0], c.cc, "/Core/CreatePipelines", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreCreatePipelinesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_CreatePipelinesClient interface {
	Recv() (*PipelineCreateResult, error)
	grpc.ClientStream
}

type coreCreatePipelinesClient struct {
	grpc.ClientStream
}

func (x *coreCreatePipelinesClient) Recv() (*PipelineCreateResult, error) {
	m := new(PipelineCreateResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreClient) ExecutePipeline(ctx context.Context, in *PipelineExecuteRequest, opts ...grpc.CallOption) (Core_ExecutePipelineClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Core_serviceDesc.Streams[1], c.cc, "/Core/ExecutePipeline", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreExecutePipelineClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_ExecutePipelineClient interface {
	Recv() (*PipelineExecuteResult, error)
	grpc.ClientStream
}

type coreExecutePipelineClient struct {
	grpc.ClientStream
}

func (x *coreExecutePipelineClient) Recv() (*PipelineExecuteResult, error) {
	m := new(PipelineExecuteResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreClient) ListPipelines(ctx context.Context, in *PipelineListRequest, opts ...grpc.CallOption) (*PipelineListResult, error) {
	out := new(PipelineListResult)
	err := grpc.Invoke(ctx, "/Core/ListPipelines", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) DeletePipelines(ctx context.Context, in *PipelineDeleteRequest, opts ...grpc.CallOption) (*PipelineListResult, error) {
	out := new(PipelineListResult)
	err := grpc.Invoke(ctx, "/Core/DeletePipelines", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) GetCreatePipelineResults(ctx context.Context, in *PipelineCreateResultsRequest, opts ...grpc.CallOption) (Core_GetCreatePipelineResultsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Core_serviceDesc.Streams[2], c.cc, "/Core/GetCreatePipelineResults", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreGetCreatePipelineResultsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_GetCreatePipelineResultsClient interface {
	Recv() (*PipelineCreateResult, error)
	grpc.ClientStream
}

type coreGetCreatePipelineResultsClient struct {
	grpc.ClientStream
}

func (x *coreGetCreatePipelineResultsClient) Recv() (*PipelineCreateResult, error) {
	m := new(PipelineCreateResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreClient) GetExecutePipelineResults(ctx context.Context, in *PipelineExecuteResultsRequest, opts ...grpc.CallOption) (Core_GetExecutePipelineResultsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Core_serviceDesc.Streams[3], c.cc, "/Core/GetExecutePipelineResults", opts...)
	if err != nil {
		return nil, err
	}
	x := &coreGetExecutePipelineResultsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Core_GetExecutePipelineResultsClient interface {
	Recv() (*PipelineExecuteResult, error)
	grpc.ClientStream
}

type coreGetExecutePipelineResultsClient struct {
	grpc.ClientStream
}

func (x *coreGetExecutePipelineResultsClient) Recv() (*PipelineExecuteResult, error) {
	m := new(PipelineExecuteResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *coreClient) ExportPipeline(ctx context.Context, in *PipelineExportRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Core/ExportPipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) UpdateProblemSchema(ctx context.Context, in *UpdateProblemSchemaRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Core/UpdateProblemSchema", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) StartSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := grpc.Invoke(ctx, "/Core/StartSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreClient) EndSession(ctx context.Context, in *SessionContext, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/Core/EndSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Core service

type CoreServer interface {
	// Train step - multiple result messages returned via GRPC streaming.
	CreatePipelines(*PipelineCreateRequest, Core_CreatePipelinesServer) error
	// Predict step - multiple results messages returned via GRPC streaming.
	ExecutePipeline(*PipelineExecuteRequest, Core_ExecutePipelineServer) error
	// Manage pipelines already present in the session.
	ListPipelines(context.Context, *PipelineListRequest) (*PipelineListResult, error)
	DeletePipelines(context.Context, *PipelineDeleteRequest) (*PipelineListResult, error)
	// Obtain results
	GetCreatePipelineResults(*PipelineCreateResultsRequest, Core_GetCreatePipelineResultsServer) error
	GetExecutePipelineResults(*PipelineExecuteResultsRequest, Core_GetExecutePipelineResultsServer) error
	// Export executable of a pipeline, including any optional preprocessing used in session
	ExportPipeline(context.Context, *PipelineExportRequest) (*Response, error)
	// Update problem schema
	UpdateProblemSchema(context.Context, *UpdateProblemSchemaRequest) (*Response, error)
	// Session management
	StartSession(context.Context, *SessionRequest) (*SessionResponse, error)
	EndSession(context.Context, *SessionContext) (*Response, error)
}

func RegisterCoreServer(s *grpc.Server, srv CoreServer) {
	s.RegisterService(&_Core_serviceDesc, srv)
}

func _Core_CreatePipelines_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineCreateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).CreatePipelines(m, &coreCreatePipelinesServer{stream})
}

type Core_CreatePipelinesServer interface {
	Send(*PipelineCreateResult) error
	grpc.ServerStream
}

type coreCreatePipelinesServer struct {
	grpc.ServerStream
}

func (x *coreCreatePipelinesServer) Send(m *PipelineCreateResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Core_ExecutePipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).ExecutePipeline(m, &coreExecutePipelineServer{stream})
}

type Core_ExecutePipelineServer interface {
	Send(*PipelineExecuteResult) error
	grpc.ServerStream
}

type coreExecutePipelineServer struct {
	grpc.ServerStream
}

func (x *coreExecutePipelineServer) Send(m *PipelineExecuteResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Core_ListPipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ListPipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/ListPipelines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ListPipelines(ctx, req.(*PipelineListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_DeletePipelines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).DeletePipelines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/DeletePipelines",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).DeletePipelines(ctx, req.(*PipelineDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_GetCreatePipelineResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineCreateResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).GetCreatePipelineResults(m, &coreGetCreatePipelineResultsServer{stream})
}

type Core_GetCreatePipelineResultsServer interface {
	Send(*PipelineCreateResult) error
	grpc.ServerStream
}

type coreGetCreatePipelineResultsServer struct {
	grpc.ServerStream
}

func (x *coreGetCreatePipelineResultsServer) Send(m *PipelineCreateResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Core_GetExecutePipelineResults_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineExecuteResultsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreServer).GetExecutePipelineResults(m, &coreGetExecutePipelineResultsServer{stream})
}

type Core_GetExecutePipelineResultsServer interface {
	Send(*PipelineExecuteResult) error
	grpc.ServerStream
}

type coreGetExecutePipelineResultsServer struct {
	grpc.ServerStream
}

func (x *coreGetExecutePipelineResultsServer) Send(m *PipelineExecuteResult) error {
	return x.ServerStream.SendMsg(m)
}

func _Core_ExportPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PipelineExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).ExportPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/ExportPipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).ExportPipeline(ctx, req.(*PipelineExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_UpdateProblemSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProblemSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).UpdateProblemSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/UpdateProblemSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).UpdateProblemSchema(ctx, req.(*UpdateProblemSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/StartSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).StartSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Core_EndSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionContext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreServer).EndSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Core/EndSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreServer).EndSession(ctx, req.(*SessionContext))
	}
	return interceptor(ctx, in, info, handler)
}

var _Core_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Core",
	HandlerType: (*CoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPipelines",
			Handler:    _Core_ListPipelines_Handler,
		},
		{
			MethodName: "DeletePipelines",
			Handler:    _Core_DeletePipelines_Handler,
		},
		{
			MethodName: "ExportPipeline",
			Handler:    _Core_ExportPipeline_Handler,
		},
		{
			MethodName: "UpdateProblemSchema",
			Handler:    _Core_UpdateProblemSchema_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _Core_StartSession_Handler,
		},
		{
			MethodName: "EndSession",
			Handler:    _Core_EndSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreatePipelines",
			Handler:       _Core_CreatePipelines_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ExecutePipeline",
			Handler:       _Core_ExecutePipeline_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCreatePipelineResults",
			Handler:       _Core_GetCreatePipelineResults_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetExecutePipelineResults",
			Handler:       _Core_GetExecutePipelineResults_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/pipeline/core.proto",
}

func init() { proto.RegisterFile("api/pipeline/core.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1936 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4b, 0x6f, 0xe3, 0xc8,
	0x11, 0xd6, 0xfb, 0x51, 0x92, 0x25, 0x4e, 0x7b, 0xc6, 0xa3, 0xf1, 0xcc, 0xec, 0xcc, 0x68, 0x2f,
	0x5e, 0x2f, 0x40, 0xaf, 0x3d, 0x58, 0x04, 0x09, 0x82, 0x64, 0x5b, 0x64, 0xcb, 0xee, 0x0c, 0x45,
	0x2a, 0x4d, 0xd2, 0x3b, 0xb3, 0x17, 0x82, 0x23, 0xb5, 0x1d, 0x61, 0x65, 0x51, 0x21, 0xa9, 0x85,
	0xf7, 0x14, 0x20, 0x40, 0xae, 0xc9, 0x39, 0x40, 0x4e, 0x01, 0xb2, 0x87, 0xdc, 0x73, 0xc8, 0x25,
	0xd7, 0xfc, 0x81, 0xfc, 0x92, 0xfd, 0x05, 0x41, 0x37, 0x49, 0x3d, 0x6c, 0xd9, 0xc8, 0x0e, 0xb0,
	0x40, 0x4e, 0x62, 0x3d, 0xba, 0xea, 0xab, 0xea, 0x2a, 0x56, 0x89, 0xf0, 0xd8, 0x9f, 0x4f, 0x8e,
	0xe6, 0x93, 0x39, 0x9f, 0x4e, 0x66, 0xfc, 0x68, 0x14, 0x84, 0x5c, 0x9d, 0x87, 0x41, 0x1c, 0xec,
	0xbf, 0xbc, 0x0c, 0x82, 0xcb, 0x29, 0x3f, 0x92, 0xd4, 0xfb, 0xc5, 0xc5, 0xd1, 0x98, 0x47, 0xa3,
	0x70, 0x32, 0x8f, 0x83, 0x30, 0xd1, 0xe8, 0x1e, 0x41, 0xcb, 0xe6, 0x51, 0x34, 0x09, 0x66, 0x5a,
	0x30, 0x8b, 0xf9, 0x75, 0x8c, 0x9e, 0x03, 0x44, 0x09, 0xc7, 0x9b, 0x8c, 0x3b, 0xf9, 0x97, 0xf9,
	0x83, 0x3a, 0xab, 0xa7, 0x1c, 0x3a, 0xee, 0x6a, 0x50, 0xb1, 0x63, 0x3f, 0x5e, 0x44, 0xe8, 0x05,
	0x94, 0x46, 0xc1, 0x98, 0x4b, 0x95, 0xd6, 0x49, 0x43, 0x4d, 0xd8, 0x5a, 0x30, 0xe6, 0x4c, 0x0a,
	0x50, 0x07, 0xaa, 0x63, 0x1e, 0xfb, 0x93, 0x69, 0xd4, 0x29, 0x48, 0x33, 0x19, 0xd9, 0xfd, 0x14,
	0x6a, 0x8c, 0x47, 0xf3, 0x60, 0x16, 0x71, 0xf4, 0x02, 0x2a, 0x91, 0x3c, 0x29, 0x0d, 0x35, 0x4e,
	0xaa, 0xa9, 0x21, 0x96, 0xb2, 0xbb, 0x74, 0x09, 0x91, 0xf1, 0xdf, 0x2e, 0x78, 0x24, 0x21, 0x2e,
	0x22, 0x1e, 0x7a, 0xfe, 0x25, 0x9f, 0xc5, 0x19, 0x44, 0xc1, 0xc1, 0x82, 0x21, 0xfc, 0x7e, 0xc3,
	0x43, 0x71, 0x20, 0xf3, 0x9b, 0x92, 0xdd, 0xbf, 0xe5, 0xa1, 0xbd, 0xb4, 0x95, 0xfa, 0x57, 0x61,
	0x27, 0x4c, 0x9f, 0xbd, 0xc9, 0xec, 0x22, 0x48, 0x61, 0xd4, 0xd5, 0x4c, 0x83, 0x35, 0x33, 0x39,
	0x9d, 0x5d, 0x04, 0x37, 0x9c, 0x17, 0xee, 0x71, 0x5e, 0xdc, 0x70, 0x8e, 0x3e, 0x81, 0xea, 0x28,
	0xc9, 0x71, 0xa7, 0x24, 0x5d, 0xb4, 0xd5, 0xcd, 0xd4, 0xb3, 0x4c, 0xde, 0xd5, 0xa0, 0xda, 0xe7,
	0x7e, 0xbc, 0x08, 0xb9, 0x70, 0x77, 0x91, 0x3c, 0xae, 0x5d, 0x47, 0xca, 0xa1, 0x63, 0xf4, 0x04,
	0x6a, 0x63, 0x3f, 0xf6, 0xbd, 0x45, 0x38, 0x59, 0x26, 0xd9, 0x8f, 0x7d, 0x37, 0x9c, 0x74, 0xff,
	0x58, 0x84, 0x47, 0xc3, 0xb4, 0x28, 0xb4, 0x90, 0xfb, 0x31, 0xcf, 0xf2, 0xb7, 0x86, 0x24, 0x7f,
	0x3f, 0x12, 0x74, 0x04, 0xad, 0x38, 0xf4, 0x27, 0x33, 0x2f, 0x75, 0x29, 0xae, 0xb2, 0x78, 0xd0,
	0x38, 0xa9, 0xa9, 0x29, 0x40, 0xb6, 0x23, 0xe5, 0x29, 0x15, 0xa1, 0xe7, 0x50, 0x8a, 0xfd, 0xe8,
	0x6b, 0x19, 0x7c, 0xeb, 0xa4, 0xae, 0x3a, 0x7e, 0xf4, 0xb5, 0xf3, 0xed, 0x9c, 0x33, 0xc9, 0x46,
	0x47, 0xd0, 0x14, 0xbf, 0x5e, 0xb4, 0x78, 0x1f, 0x7f, 0x3b, 0xe7, 0x32, 0x13, 0xad, 0x93, 0xa6,
	0x54, 0xb3, 0x13, 0x1e, 0x6b, 0xc4, 0x2b, 0x02, 0x7d, 0x02, 0x8a, 0x3c, 0x90, 0x55, 0xae, 0x48,
	0x6c, 0x59, 0x06, 0xda, 0x16, 0x7c, 0x7d, 0xc5, 0x46, 0x1f, 0x43, 0x25, 0x58, 0xc4, 0xf3, 0x45,
	0xdc, 0xa9, 0xa4, 0x25, 0x69, 0x49, 0x52, 0xba, 0x4f, 0x45, 0xe8, 0x15, 0x54, 0xaf, 0x78, 0x1c,
	0x4e, 0x46, 0x51, 0xa7, 0xfa, 0xb2, 0x78, 0xd0, 0x3a, 0xa9, 0xaa, 0x03, 0x49, 0xb3, 0x8c, 0x8f,
	0x8e, 0xa1, 0x1d, 0xfb, 0xe1, 0x25, 0x8f, 0x57, 0x41, 0xd7, 0x6e, 0x04, 0xdd, 0x4a, 0x14, 0x96,
	0x51, 0x7f, 0x0c, 0x3b, 0x57, 0xfe, 0xb5, 0x97, 0xf5, 0x60, 0xd4, 0xa9, 0xbf, 0xcc, 0x1f, 0x94,
	0x59, 0xf3, 0xca, 0xbf, 0xce, 0xae, 0x20, 0xea, 0xfe, 0x02, 0xca, 0xb6, 0x68, 0x4e, 0x51, 0xf2,
	0x89, 0xaf, 0xb4, 0x77, 0x96, 0x10, 0x52, 0x36, 0x7a, 0x08, 0xe5, 0x6f, 0xfc, 0xe9, 0x82, 0xcb,
	0x2b, 0x2d, 0xb0, 0x84, 0xe8, 0xfe, 0x0e, 0x6a, 0x99, 0x31, 0xa4, 0xc2, 0xee, 0x3c, 0xe4, 0xe3,
	0xc9, 0x28, 0xf6, 0x42, 0x1e, 0x2d, 0xa6, 0xb1, 0xa8, 0x00, 0xd1, 0x42, 0xc5, 0x83, 0x3a, 0x7b,
	0x90, 0x8a, 0x98, 0x94, 0xb8, 0xe1, 0x24, 0x5a, 0xcb, 0x4d, 0xe1, 0xee, 0xdc, 0x7c, 0x04, 0x95,
	0x48, 0x00, 0x8c, 0x3a, 0x45, 0x19, 0x6f, 0x45, 0x95, 0x78, 0x59, 0xca, 0xed, 0xfe, 0x3b, 0x0f,
	0x0f, 0x6f, 0x56, 0x94, 0xf0, 0xf0, 0x83, 0x7b, 0x48, 0x85, 0x9d, 0x79, 0x18, 0x5c, 0x86, 0x3c,
	0x8a, 0x12, 0xfd, 0x42, 0x5a, 0x2d, 0xc3, 0x94, 0xcb, 0x9a, 0x99, 0x5c, 0xea, 0xbf, 0x80, 0x46,
	0x96, 0x5a, 0xd1, 0x05, 0x49, 0x63, 0x41, 0xc6, 0xa2, 0x63, 0x69, 0x70, 0xa9, 0x20, 0x0c, 0x96,
	0x52, 0x00, 0x19, 0x5c, 0xd6, 0x5c, 0x6a, 0xcf, 0x2e, 0x82, 0xee, 0x9f, 0xf3, 0xb0, 0x97, 0x89,
	0xc8, 0x35, 0x1f, 0x2d, 0x3e, 0xa8, 0x39, 0x6e, 0xc0, 0x2a, 0xdc, 0x82, 0xf5, 0x1a, 0x94, 0xec,
	0x96, 0x96, 0xa5, 0x54, 0xbc, 0x51, 0x4a, 0xed, 0x54, 0x23, 0xab, 0xa5, 0xee, 0x3f, 0xf3, 0xab,
	0xbe, 0x5d, 0x62, 0xfb, 0xff, 0x48, 0xf3, 0x0b, 0x68, 0xac, 0x57, 0x5b, 0x49, 0x56, 0x1b, 0x84,
	0xcb, 0x32, 0xeb, 0x7e, 0x01, 0xbb, 0x19, 0x74, 0x63, 0x12, 0xc5, 0x3f, 0x3c, 0xa7, 0xdd, 0x70,
	0x15, 0xbc, 0xce, 0xa7, 0xfc, 0x83, 0xee, 0x45, 0x85, 0xdd, 0xb1, 0x3c, 0xeb, 0xad, 0x85, 0x93,
	0xbc, 0xb9, 0xea, 0xec, 0x41, 0x22, 0x1a, 0x2e, 0xa3, 0x8a, 0xba, 0x97, 0x80, 0x36, 0x51, 0x7f,
	0x50, 0xb6, 0x5f, 0x41, 0x73, 0x8b, 0xbb, 0xc6, 0x7c, 0xcd, 0xd1, 0x14, 0x9e, 0x6d, 0xeb, 0x9f,
	0xe8, 0x03, 0x62, 0xfc, 0x1f, 0xbc, 0x5d, 0xc1, 0xf3, 0xad, 0x75, 0xf4, 0x23, 0xb9, 0xfb, 0xd3,
	0x46, 0xdd, 0xce, 0x83, 0x30, 0xfe, 0x31, 0x5a, 0xea, 0x10, 0x1e, 0x2c, 0x15, 0xf8, 0x35, 0x1f,
	0xc9, 0xc9, 0x97, 0x54, 0x6a, 0x7b, 0xbe, 0x16, 0xad, 0x98, 0x80, 0xdf, 0x17, 0x60, 0xdf, 0x9d,
	0x8f, 0xfd, 0x98, 0x0f, 0xc3, 0xe0, 0xfd, 0x94, 0x5f, 0xd9, 0xa3, 0xdf, 0xf0, 0x2b, 0x3f, 0x83,
	0x65, 0x41, 0x75, 0x21, 0xa5, 0xc9, 0x7b, 0xb3, 0x71, 0xf2, 0xb9, 0x7a, 0xb7, 0xb6, 0xca, 0xf8,
	0x7c, 0xea, 0x8f, 0x36, 0x65, 0xfd, 0x09, 0x9f, 0x8e, 0x59, 0x66, 0x65, 0xff, 0xf7, 0x05, 0x78,
	0x72, 0xa7, 0x1a, 0x3a, 0x80, 0xba, 0x9c, 0x64, 0x72, 0xee, 0xe5, 0x6f, 0x8c, 0xc7, 0xb3, 0x1c,
	0xab, 0xc5, 0xe9, 0x33, 0x3a, 0xbe, 0x31, 0x24, 0x0b, 0xb7, 0x87, 0xe4, 0x59, 0x6e, 0x73, 0x4c,
	0x7e, 0xba, 0x65, 0x4c, 0xca, 0xac, 0x9c, 0xe5, 0x6e, 0x0f, 0x4a, 0x15, 0x1a, 0xc9, 0x1b, 0xdf,
	0x5b, 0x9b, 0xc1, 0xeb, 0x13, 0xe1, 0x2c, 0xc7, 0x20, 0x58, 0x52, 0xe8, 0xd5, 0x72, 0x5e, 0x95,
	0x37, 0xe6, 0xd5, 0x59, 0x2e, 0x9b, 0x58, 0xbd, 0x1a, 0x54, 0x92, 0x2c, 0x1c, 0xfe, 0xa1, 0x00,
	0xb0, 0x5a, 0x05, 0x51, 0x03, 0xaa, 0xae, 0xf9, 0xc6, 0xb4, 0xbe, 0x34, 0x95, 0x1c, 0xaa, 0x40,
	0xc1, 0x7a, 0xa3, 0xe4, 0xd1, 0x0e, 0xd4, 0x35, 0x6c, 0x6a, 0xc4, 0x30, 0x88, 0xae, 0x14, 0xd0,
	0x2e, 0xb4, 0x6d, 0x62, 0xdb, 0xd4, 0x32, 0xbd, 0x4c, 0xb7, 0x88, 0x1e, 0xc0, 0x4e, 0xc6, 0x24,
	0xa6, 0x4e, 0x74, 0xa5, 0xb4, 0xae, 0x47, 0xde, 0x0e, 0x29, 0x23, 0xba, 0x52, 0x46, 0x0f, 0x41,
	0xa1, 0xe6, 0x39, 0x36, 0xa8, 0xee, 0x61, 0x76, 0xea, 0x0e, 0x88, 0xe9, 0x28, 0x15, 0xb4, 0x07,
	0x88, 0x11, 0xdb, 0x72, 0x99, 0x46, 0x3c, 0xf2, 0xf6, 0x0c, 0xbb, 0xb6, 0x43, 0x74, 0xa5, 0x8a,
	0xda, 0xd0, 0x70, 0x4d, 0x7c, 0x8e, 0xa9, 0x81, 0x7b, 0x06, 0x51, 0x6a, 0xe8, 0x31, 0xec, 0xf6,
	0x31, 0x35, 0x88, 0xee, 0x0d, 0x19, 0xd1, 0x2c, 0x53, 0xa7, 0x0e, 0xb5, 0x4c, 0xa5, 0x8e, 0x14,
	0x68, 0x5a, 0xae, 0xe3, 0x59, 0x7d, 0x8f, 0x61, 0xf3, 0x94, 0x28, 0x20, 0x10, 0xb9, 0x26, 0x1d,
	0x0c, 0x0d, 0x22, 0x9c, 0x10, 0x5d, 0x69, 0xa0, 0x26, 0xd4, 0xa8, 0xe9, 0x10, 0x66, 0x62, 0x43,
	0x69, 0x8a, 0x58, 0x71, 0xcf, 0x62, 0x42, 0xb4, 0x73, 0xd8, 0x83, 0x5a, 0xf6, 0x9a, 0x15, 0xf1,
	0xda, 0x6e, 0x6f, 0x40, 0x1d, 0x21, 0xca, 0x09, 0x3d, 0xe6, 0x9a, 0x26, 0x35, 0x4f, 0x95, 0xbc,
	0x4c, 0xd0, 0x50, 0xc7, 0x8e, 0xcc, 0x84, 0x48, 0x8c, 0x25, 0x3c, 0x08, 0xb2, 0x78, 0xf8, 0x7d,
	0x1e, 0x6a, 0x59, 0x85, 0x08, 0xa4, 0x0e, 0xb6, 0xdf, 0x78, 0xce, 0xbb, 0x21, 0xf1, 0x5c, 0x53,
	0x27, 0x7d, 0x6a, 0x4a, 0x73, 0x08, 0x5a, 0x9a, 0x81, 0x6d, 0x9b, 0xf6, 0xa9, 0x86, 0x25, 0xfa,
	0x3c, 0x6a, 0x01, 0x30, 0x72, 0xca, 0x92, 0x6c, 0x29, 0x05, 0x71, 0xd8, 0xa6, 0x03, 0x6a, 0x60,
	0x46, 0x9d, 0x77, 0xde, 0x00, 0x3b, 0xda, 0x99, 0x70, 0x5f, 0x14, 0x39, 0x35, 0xa8, 0xf9, 0x46,
	0x44, 0xaf, 0x53, 0x4d, 0x9e, 0x2e, 0xa1, 0x47, 0xf0, 0xe0, 0x9c, 0x30, 0x87, 0xbc, 0xf5, 0x4c,
	0x6b, 0x40, 0xcd, 0xc4, 0x68, 0x59, 0x18, 0xd1, 0xac, 0xc1, 0xc0, 0x35, 0x85, 0x0d, 0x9d, 0x38,
	0x24, 0xd1, 0xaf, 0x08, 0x04, 0xa7, 0x0c, 0x0f, 0xcf, 0x56, 0x86, 0xab, 0x68, 0x1f, 0xf6, 0x1c,
	0x3a, 0x20, 0x36, 0x61, 0x94, 0xd8, 0x5e, 0xdf, 0x62, 0x44, 0xc3, 0xb6, 0x23, 0x64, 0x35, 0xf4,
	0x14, 0x1e, 0x6b, 0x96, 0x61, 0x88, 0x64, 0x61, 0x87, 0x9e, 0x13, 0xaf, 0x4f, 0x0d, 0x87, 0x30,
	0x21, 0xac, 0x1f, 0x7e, 0x97, 0x87, 0xc6, 0x5a, 0xa5, 0x4b, 0x43, 0x22, 0x6e, 0xdb, 0xed, 0xdd,
	0x0a, 0xbd, 0x06, 0x25, 0xd3, 0x32, 0x89, 0x92, 0x47, 0x00, 0x95, 0x1e, 0x35, 0x31, 0x7b, 0xa7,
	0x14, 0x44, 0xf0, 0x03, 0xd7, 0x70, 0xa8, 0xcc, 0x8a, 0x52, 0x5c, 0xd2, 0x06, 0xee, 0x11, 0x43,
	0x29, 0x09, 0xda, 0x35, 0xe9, 0x39, 0x66, 0x14, 0x3b, 0x44, 0x29, 0x8b, 0xab, 0x96, 0xf2, 0x8c,
	0x53, 0x11, 0x65, 0x62, 0x9d, 0x13, 0x66, 0xe0, 0xe1, 0x30, 0x89, 0x06, 0x41, 0xcb, 0xb4, 0xcc,
	0x75, 0x5e, 0xed, 0xf0, 0xef, 0x79, 0x80, 0x55, 0xcf, 0xa0, 0x27, 0xf0, 0xc8, 0x72, 0x9d, 0xa1,
	0xeb, 0xdc, 0xbe, 0xa1, 0x36, 0x34, 0x24, 0x16, 0x2f, 0x41, 0x90, 0x17, 0x8c, 0x21, 0xb3, 0x7a,
	0xb8, 0x47, 0x0d, 0xea, 0x08, 0xc8, 0x35, 0x28, 0x31, 0x82, 0x0d, 0xa5, 0x28, 0xea, 0xc1, 0xb4,
	0x74, 0xe2, 0x51, 0x51, 0xf1, 0x7b, 0x80, 0xce, 0x89, 0xe6, 0x58, 0xcc, 0x5b, 0x3f, 0x5f, 0x4e,
	0x2e, 0x48, 0xf2, 0x6d, 0xc7, 0xd2, 0xce, 0x44, 0x62, 0xb5, 0x04, 0x76, 0xca, 0x96, 0xc6, 0xaa,
	0xc2, 0x6c, 0x9f, 0x8a, 0x3a, 0x3f, 0xfc, 0x57, 0x01, 0x2a, 0x83, 0x6c, 0xbb, 0x54, 0x06, 0xc4,
	0x61, 0x54, 0xdb, 0xc0, 0xd8, 0x84, 0x1a, 0xd6, 0x34, 0x97, 0x61, 0xed, 0x9d, 0x92, 0x17, 0x9d,
	0xda, 0x3f, 0x56, 0x0a, 0x82, 0xdb, 0x3f, 0xf6, 0x06, 0x54, 0x63, 0x96, 0x52, 0xcc, 0x28, 0x2c,
	0xa8, 0x92, 0x2c, 0x63, 0x4b, 0xf3, 0xb0, 0xab, 0x29, 0x65, 0xd1, 0x1c, 0x29, 0x91, 0x6a, 0x57,
	0x36, 0x58, 0xf2, 0x48, 0x55, 0x5c, 0x3c, 0xb3, 0x2c, 0xc7, 0x1b, 0x10, 0x6c, 0x7a, 0xf6, 0xaf,
	0x5d, 0xcc, 0x88, 0xee, 0x11, 0xc6, 0x2c, 0xa6, 0xd4, 0xd0, 0x0b, 0x78, 0x7a, 0x87, 0xd0, 0xc3,
	0xe7, 0xa7, 0x4a, 0x5d, 0xd4, 0x9f, 0x94, 0xe1, 0x9e, 0x6d, 0x19, 0xae, 0x43, 0xd2, 0x93, 0x20,
	0xda, 0x86, 0x65, 0x27, 0x94, 0x06, 0x7a, 0x05, 0xcf, 0x4d, 0x8b, 0x0d, 0xb0, 0x41, 0xbf, 0x22,
	0xba, 0x37, 0x70, 0x1d, 0x17, 0x1b, 0x1e, 0x35, 0xfb, 0x82, 0x27, 0x2b, 0xb6, 0x89, 0x9e, 0x41,
	0xe7, 0x57, 0x58, 0xd3, 0x30, 0xd3, 0xbd, 0xb5, 0xbe, 0xb0, 0x35, 0x8b, 0x11, 0x65, 0x47, 0xdc,
	0x36, 0x79, 0x4b, 0x34, 0x57, 0x28, 0x7b, 0xa2, 0x8a, 0x95, 0xd6, 0xc9, 0x5f, 0xca, 0x50, 0xd2,
	0xc4, 0xf6, 0xae, 0x43, 0x3b, 0x19, 0xde, 0xcb, 0xcd, 0x1e, 0xed, 0xa9, 0x5b, 0xff, 0x68, 0xed,
	0x3f, 0x52, 0xb7, 0x8d, 0xfb, 0x6e, 0xee, 0xb3, 0x3c, 0xea, 0x43, 0x3b, 0x1d, 0xca, 0xcb, 0x9d,
	0xfe, 0xb1, 0xba, 0x7d, 0x25, 0xdd, 0xdf, 0x53, 0xb7, 0xce, 0x71, 0x69, 0xe7, 0xe7, 0xb0, 0x23,
	0x76, 0x96, 0x15, 0x96, 0x87, 0xea, 0x96, 0x0d, 0x6c, 0x7f, 0x57, 0xbd, 0xbd, 0xe1, 0x74, 0x73,
	0xe8, 0x0b, 0x68, 0xeb, 0x1b, 0xeb, 0xd0, 0x7a, 0x2c, 0x1b, 0xfb, 0xd7, 0x5d, 0x16, 0x1c, 0xe8,
	0x9c, 0xf2, 0x78, 0x33, 0x21, 0xe9, 0x9a, 0x81, 0x9e, 0xab, 0xf7, 0x6d, 0x3b, 0xf7, 0x65, 0xe7,
	0x4b, 0x78, 0x72, 0xca, 0xe3, 0x1b, 0x09, 0xca, 0xcc, 0x7e, 0xa4, 0xde, 0xbb, 0xd6, 0xdc, 0x9b,
	0xae, 0xcf, 0xa1, 0x95, 0xec, 0x26, 0xcb, 0xac, 0xaf, 0x6b, 0xaf, 0x2d, 0x2d, 0xfb, 0xab, 0x3d,
	0xaf, 0x9b, 0x43, 0xbf, 0x84, 0xdd, 0x2d, 0xab, 0x01, 0x7a, 0x7a, 0xcf, 0xc2, 0xb0, 0x69, 0xe0,
	0x35, 0x34, 0xed, 0xd8, 0x0f, 0xe3, 0x74, 0xef, 0x41, 0xcb, 0x0d, 0x28, 0xd3, 0x56, 0xd4, 0x1b,
	0x1f, 0x26, 0xba, 0x39, 0x74, 0x08, 0x40, 0x66, 0xe3, 0x5b, 0x47, 0xd2, 0xa5, 0x69, 0xc3, 0xc1,
	0xcf, 0xa8, 0xf8, 0xab, 0x11, 0xc4, 0xc1, 0x28, 0x98, 0x7a, 0xd9, 0x17, 0x87, 0x67, 0x6a, 0xf2,
	0xfd, 0x47, 0xcd, 0xbe, 0xff, 0xa8, 0xfd, 0xc9, 0x94, 0x5b, 0x72, 0x09, 0x88, 0x3a, 0xff, 0xf9,
	0x2e, 0x5b, 0x9b, 0xd2, 0x73, 0xe7, 0xc9, 0xb1, 0xde, 0xe3, 0xbf, 0xfe, 0x63, 0xbf, 0x7e, 0xf2,
	0xd9, 0xf1, 0x4f, 0xd4, 0x9f, 0xaa, 0xc7, 0xc7, 0x5f, 0xd5, 0xb2, 0xb5, 0xea, 0x7d, 0x45, 0x6a,
	0xbe, 0xfe, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x4c, 0xc4, 0x6d, 0x70, 0x12, 0x00, 0x00,
}
